---
- hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'update printnanny cli'
    ara_playbook_labels:
      - update
      - printnanny
      - 'component:secret'
      - 'component:janus'
  name: Update Print Nanny Secrets
  tasks:
    - name: Include roles/printnanny/defaults
      include_vars: ../../../roles/printnanny/defaults/main.yml
    - name: Include roles/printnanny/vars
      include_vars: ../../../roles/printnanny/vars/main.yml
    - name: Update Janus Secrets
      include_role:
        name: bitsyai.rpi.janus
        tasks_from: secrets
    - name: Generate Print Nanny certificates
      include_role:
        name: bitsyai.rpi.printnanny
        tasks_from: cert
- hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'update printnanny janus'
    ara_playbook_labels:
      - update
      - printnanny
      - 'component:janus'
  tasks:
    - name: Include roles/printnanny/defaults
      include_vars: ../../../roles/printnanny/defaults/main.yml
    - name: Include roles/printnanny/vars
      include_vars: ../../../roles/printnanny/vars/main.yml
    - name: Update Janus Gateway
      include_role:
        name: bitsyai.rpi.janus
