---
- hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'update printnanny janus'
    ara_playbook_labels:
      - update
      - printnanny
      - 'component:janus'
  tasks:
    - name: Include roles/printnanny/vars
      include_vars: ../../roles/printnanny/vars/main.yml
    - name: Update Janus Gateway
      include_role:
        name: bitsyai.rpi.janus
