---
- hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'update printnanny system'
    ara_playbook_labels:
      - update
      - printnanny
      - system
  roles:
    - bitsyai.rpi.common
    - bitsyai.rpi.printnanny
    - bitsyai.rpi.janus
