---
- hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'update printnanny system'
    ara_playbook_labels:
      - update
      - printnanny
      - system
  tasks:
    - name: Include roles/printnanny/vars
      include_vars: ../../../roles/printnanny/vars/main.yml
    - name: Common Raspberry Pi setup
      include_role:
        name: bitsyai.rpi.common
    - name: Print Nanny setup
      include_role:
        name: bitsyai.rpi.printnanny
    - name: Automatic software update setup
      include_role:
        name: bitsyai.rpi.updater
    - name: Camera setup
      include_role:
        name: bitsyai.rpi.camera
    - name: Janus Gateway setup
      include_role:
        name: bitsyai.rpi.janus
