---
- name: Update Print Nanny system
  import_playbook: ../system.yml
  vars:
    printnanny_edition: octoprint_desktop
    janus_remote_enabled: true
    janus_local_enabled: false
- hosts: printnanny
  tasks:
    - name: Install firstboot service
      include_role:
        name: bitsyai.printnanny.metadata
        tasks_from: install/firstboot.yml
      tags:
        - packer
    - name: Clean and minimize image
      include_role:
        name: bitsyai.printnanny.common
        tasks_from: clean_image
      tags:
        - packer
