---
- name: Update PrintNanny system
  import_playbook: ../system.yml
  vars:
    printnanny_edition: octoprint_desktop
    janus_cloud_enabled: true
    janus_local_enabled: false
- hosts: printnanny
  tasks:
    - name: Clean and minimize image
      include_role:
        name: bitsyai.printnanny.common
        tasks_from: clean_image
      tags:
        - packer
