- name: Install sudo pkg
  become: true
  ansible.builtin.apt:
    name:
      - sudo
  tags:
    - setup

- name: Install apt dependencies
  become: true
  ansible.builtin.apt:
    name:
      - pkg-config
      - python3-dev
      - python3-pip
      - python3-venv
      # required by ansible.builtin.package_facts
      - python3-apt
      - systemd
      - systemd-cron
  tags:
    - setup

- name: Create /etc/ansible
  become: true
  ansible.builtin.file:
    path: /etc/ansible
    state: directory
    mode: 0755
  tags:
    - setup

- name: 'Update ansible virtualenv pip, setuptools'
  ansible.builtin.pip:
    name:
      - 'pip>21,<22'
      - setuptools
      - wheel
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ updater_venv }}'
    extra_args: '--no-cache-dir'
  tags:
    - setup

- name: Install ansible into virtual env
  ansible.builtin.pip:
    name: '{{ ansible_updater_version }}'
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ updater_venv }}'
    extra_args: '--no-cache-dir'
  tags:
    - setup
    - requirements

# get ara configuration before rendering ansible.cfg (if enabled)
- name: Configure ara
  ansible.builtin.include_tasks: update/ara.yml
  when: ara_enabled

- name: Create ansible.cfg
  become: true
  ansible.builtin.template:
    mode: 0755
    src: ansible/ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
    force: true
  tags:
    - setup

- name: Create printnanny-metadata service
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/printnanny-metadata.service.j2
    dest: /etc/systemd/system/printnanny-metadata.service
    force: true
  tags:
    - setup

- name: Create printnanny-metadata target
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/printnanny-metadata.target.j2
    dest: /etc/systemd/system/printnanny-metadata.target
    force: true
  tags:
    - setup

- name: Enable printnanny-metadata unit
  become: true
  ansible.builtin.systemd:
    name: printnanny-metadata
    enabled: true
    no_block: true
  tags:
    - setup

- name: Create printnanny-update service
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/printnanny-update.service.j2
    dest: /etc/systemd/system/printnanny-update.service
    force: true
  tags:
    - setup

- name: Create printnanny-update target
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/printnanny-update.target.j2
    dest: '/etc/systemd/system/printnanny-update.target'
    force: true
  tags:
    - setup

- name: Enable printnanny-update unit
  become: true
  ansible.builtin.systemd:
    name: 'printnanny-update'
    enabled: true
    no_block: true
  tags:
    - setup
  notify:
    - restart printnanny-update

- name: Render printnanny.target
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/printnanny.target.j2
    dest: /etc/systemd/system/printnanny.target
    force: true
  tags:
    - setup

- name: Set updater service enabled
  become: true
  ansible.builtin.systemd:
    name: printnanny
    enabled: true
    no_block: true
  tags:
    - setup

- name: Create ansible pull hosts
  become: true
  ansible.builtin.copy:
    src: files/hosts
    dest: '{{ ansible_hosts_file }}'
    mode: 0755
  tags:
    - setup

- name: Create {{ ansible_facts_path }}
  become: true
  ansible.builtin.file:
    path: '{{ ansible_facts_path }}'
    state: directory
    mode: 0755

- name: Render /etc/ansible/facts.d/device.fact
  become: true
  ansible.builtin.copy:
    src: facts.d/device.fact
    dest: '{{ printnanny_device_fact }}'
    mode: 0755

- name: Render printnanny-update.sh
  become: true
  ansible.builtin.template:
    src: printnanny-update.sh.j2
    dest: /usr/local/bin/printnanny-update
    force: true
    mode: 0775
