- name: Set OctoPrint version facts
  ansible.builtin.set_fact:
    octoprint_pip_version: '{{ octoprint_pip_version }}'
    octoprint_python_version: '{{ octoprint_python_version }}'
    cacheable: true
