---
# tasks file for octoprint
- name: Install apt dependencies
  become: true
  ansible.builtin.apt:
    name:
      - pkg-config
      - python3-dev
      - python3-pip
      - python3-venv
  tags:
    - setup
    - system-update
    - octoprint

- name: Create octoprint user
  become: true
  ansible.builtin.user:
    name: "{{ octoprint_user }}"
    state: present
    shell: /bin/bash
    comment: "OctoPrint service user"
    groups:
      - adm
      - dialout
      - gpio
      - i2c
      - input
      - plugdev
      - spi
      - sudo
      - tty
      - video
  tags:
    - setup
    - system-update
    - octoprint

- name: Create {{ octoprint_dir }}
  become: true
  ansible.builtin.file:
    state: directory
    path: '{{ octoprint_dir }}'
    mode: 0775
    owner: '{{ octoprint_user }}'
    group: '{{ octoprint_user }}'
  tags:
    - setup
    - system-update
    - octoprint

- name: Create {{ octoprint_log_dir }}
  become: true
  ansible.builtin.file:
    state: directory
    path: '{{ octoprint_log_dir }}'
    mode: 0664
    owner: '{{ octoprint_user }}'
    group: '{{ octoprint_user }}'
  tags:
    - setup
    - system-update
    - octoprint

- name: Create {{ octoprint_watched_dir }}
  become: true
  ansible.builtin.file:
    state: directory
    path: '{{ octoprint_watched_dir }}'
    mode: 0664
    owner: '{{ octoprint_user }}'
    group: '{{ octoprint_user }}'
  tags:
    - setup
    - system-update
    - octoprint

- name: 'Create Octoprint virtualenv'
  become: true
  become_user: '{{ octoprint_user }}'
  ansible.builtin.pip:
    name:
      - 'pip>21,<22'
      - setuptools
      - wheel
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ octoprint_venv }}'
    extra_args: '--no-cache-dir'
  tags:
    - setup
    - system-update
    - octoprint

- name: Install OctoPrint (release)
  include_tasks: plugin_release.yml
  when: not octoprint_printnanny_plugin_dev

- name: Install OctoPrint (developer mode)
  include_tasks: plugin_dev.yml
  when: octoprint_printnanny_plugin_dev

- name: Render octoprint config
  become_user: '{{ octoprint_user }}'
  ansible.builtin.template:
    mode: 0664
    src: config.yml.j2
    dest: '{{ octoprint_config }}'
    force: true
    owner: '{{ octoprint_user }}'
    group: '{{ octoprint_user }}'
  tags:
    - setup
    - system-update
    - octoprint

- name: Include nginx tasks
  include_tasks: nginx.yml
