---
# tasks file for octoprint
- name: Install apt dependencies
  become: true
  ansible.builtin.apt:
    name:
        - pkg-config 
        - python3-dev
        - python3-pip
        - python3-venv

- name: Create octoprint user
  ansible.builtin.user:
    name: "{{ octoprint_user }}"
    state: present
    shell: /sbin/nologin
    comment: "Octoprint service user"
  become: true

- name: 'Create Octoprint virtualenv'
  become_user: '{{ octoprint_user }}'
  pip:
    name:
      - 'pip>21,<22'
      - setuptools
      - wheel
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ octoprint_venv }}'
    extra_args: '--no-cache-dir'

- name: Install octoprint into venv
  become_user: '{{ octoprint_user }}'
  pip:
    name: '{{ octoprint_version }}'
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ octoprint_venv }}'
    extra_args: '--no-cache-dir'