---
# tasks file for octoprint
- name: Install apt dependencies
  become: true
  ansible.builtin.apt:
    name:
      - pkg-config
      - python3-dev
      - python3-pip
      - python3-venv
  tags:
    - setup
    - system-update
    - octoprint


- name: Create {{ octoprint_dir }}
  become: true
  ansible.builtin.file:
    state: directory
    path: '{{ octoprint_dir }}'
    mode: 0775
    owner: '{{ octoprint_user }}'
    group: '{{ octoprint_user }}'
  tags:
    - setup
    - system-update
    - octoprint

- name: Create {{ octoprint_log_dir }}
  become: true
  ansible.builtin.file:
    state: directory
    path: '{{ octoprint_log_dir }}'
    mode: 0775
    owner: '{{ octoprint_user }}'
    group: '{{ octoprint_user }}'
  tags:
    - setup
    - system-update
    - octoprint

- name: 'Create Octoprint virtualenv'
  become: true
  become_user: '{{ octoprint_user }}'
  ansible.builtin.pip:
    name:
      - 'pip>21,<22'
      - setuptools
      - wheel
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ octoprint_venv }}'
    extra_args: '--no-cache-dir'
  tags:
    - setup
    - system-update
    - octoprint

- name: Install OctoPrint (release)
  include_tasks: plugin_release.yml
  when: not octoprint_plugin_dev

- name: Install OctoPrint (developer mode)
  include_tasks: plugin_dev.yml
  when: octoprint_plugin_dev

- name: Render octoprint config
  become_user: '{{ octoprint_user }}'
  ansible.builtin.template:
    mode: 0664
    src: config.yaml.j2
    dest: '{{ octoprint_config }}'
    force: true
    owner: '{{ octoprint_user }}'
    group: '{{ octoprint_user }}'
  tags:
    - setup
    - system-update
    - octoprint

- name: Include nginx tasks
  include_tasks: nginx.yml

# symlink creates an alias in systemd, allowing printnanny* to be used in systemctl and journalctl filters
- name: symlink octoprint.service to printnanny-octoprint.service
  become: true
  ansible.builtin.file:
    src: /etc/systemd/system/octoprint.service
    dest: /etc/systemd/system/printnanny-octoprint.service
    state: link

- name: Include plugin dev tasks
  include_tasks: plugin_dev.yml

- name: Get installed python_version
  ansible.builtin.command:
    cmd: "{{ octoprint_venv }}/bin/python3 -c 'import platform; print(platform.python_version())'"
  when: printnanny_edition == "octoprint_desktop" or printnanny_edition == "octoprint_lite"
  register: octoprint_python_version

- name: Get installed pip version
  ansible.builtin.command:
    cmd: "{{ octoprint_venv }}/bin/python3 -c 'import pip; print(pip.__version__)'"
  when: printnanny_edition == "octoprint_desktop" or printnanny_edition == "octoprint_lite"
  register: octoprint_pip_version

- name: Set OctoPrint version facts
  ansible.builtin.set_fact:
    octoprint_pip_version: '{{ octoprint_pip_version }}'
    octoprint_python_version: '{{ octoprint_python_version }}'
    octoprint_git_version: '{{ octoprint_git_version }}'
    octoprint_printnanny_plugin_version: '{{ octoprint_printnanny_plugin_version }}'
    octoprint_venv: '{{ octoprint_venv }}'
    cacheable: true
