- name: Configure git.user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: '{{ octoprint_plugin_git_email }}'

- name: Configure git.user.email
  community.general.git_config:
    name: user.name
    scope: global
    value: '{{ octoprint_plugin_git_name }}'

- name: Configure authorized_keys (developer mode)
  ansible.posix.authorized_key:
    key: '{{ octoprint_plugin_git_keys }}'
    user: '{{ octoprint_user }}'

- name: Clone OctoPrint (developer mode)
  become: true
  become_user: '{{ octoprint_user }}'
  ansible.builtin.git:
    repo: '{{ octoprint_repo }}'
    dest: '{{ octoprint_repo_dir }}'
    version: '{{ octoprint_git_version }}'
  tags:
    - setup
    - system-update
    - octoprint
  when: octoprint_printnanny_plugin_dev

- name: Install OctoPrint (developer mode)
  become: true
  become_user: '{{ octoprint_user }}'
  ansible.builtin.pip:
    name: '.[develop,plugins]'
    virtualenv: '{{ octoprint_venv }}'
    editable: true
    chdir: '{{ octoprint_repo_dir }}'
  tags:
    - setup
    - system-update
    - octoprint
  when: octoprint_printnanny_plugin_dev

- name: Clone OctoPrint plugin (developer mode)
  become: true
  become_user: '{{ octoprint_user }}'
  ansible.builtin.git:
    repo: '{{ octoprint_plugin_git_repo }}'
    dest: '{{ octoprint_printnanny_plugin_dir }}'
    version: '{{ octoprint_printnanny_plugin_version }}'
    accept_hostkey: true
  tags:
    - setup
    - system-update
    - octoprint
  when: octoprint_printnanny_plugin_dev

- name: Install OctoPrint plugin (developer mode)
  become: true
  become_user: '{{ octoprint_user }}'
  ansible.builtin.pip:
    name: '.'
    virtualenv: '{{ octoprint_venv }}'
    editable: true
    chdir: '{{ octoprint_printnanny_plugin_dir }}'
  tags:
    - setup
    - system-update
    - octoprint
  when: octoprint_printnanny_plugin_dev
