- name: Install octoprint into venv
  become: true
  become_user: '{{ octoprint_user }}'
  ansible.builtin.pip:
    name: '{{ octoprint_pip_version }}'
    virtualenv: '{{ octoprint_venv }}'
    extra_args: '--no-cache-dir'
  tags:
    - setup
    - system-update
    - octoprint
  when: not octoprint_plugin_dev

# If OctoPrint is not installed first, plugin installation fails with the following erorr:
## Could not import OctoPrint's setuptools,
## are you sure you are running that under the same python installation that OctoPrint is installed under?\n    ----------------------------------------\n
- name: Install OctoPrint plugin into venv (required to detect OctoPrint setuptools)
  become: true
  become_user: '{{ octoprint_user }}'
  pip:
    name: '{{ octoprint_printnanny_pip_install }}'
    virtualenv: '{{ octoprint_venv }}'
    extra_args: '--no-cache-dir'
  tags:
    - setup
    - system-update
    - octoprint
  when: not octoprint_plugin_dev

- name: Render octoprint.service template
  become: true
  ansible.builtin.template:
    mode: 0664
    src: octoprint.service.j2
    dest: '/etc/systemd/system/octoprint.service'
    force: true
  notify:
    - restart octoprint
  tags:
    - setup
    - system-update
    - octoprint

- name: Enable octoprint.service
  become: true
  ansible.builtin.systemd:
    name: octoprint.service
    state: started
    enabled: true
    no_block: true
  tags:
    - setup
    - system-update
    - octoprint
