- name: Render printnanny-octoprint-plugin-dev
  become: true
  ansible.builtin.template:
    src: octoprint-plugin-dev.sh.j2
    mode: 0775
    dest: /usr/local/bin/printnanny-octoprint-plugin-dev

- name: Configure git.user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: '{{ octoprint_plugin_git_email }}'
  when: octoprint_plugin_dev

- name: Configure git.user.email
  community.general.git_config:
    name: user.name
    scope: global
    value: '{{ octoprint_plugin_git_name }}'
  when: octoprint_plugin_dev

- name: Configure authorized_keys (developer mode)
  ansible.posix.authorized_key:
    key: '{{ octoprint_plugin_git_keys }}'
    user: '{{ octoprint_user }}'
  when: octoprint_plugin_dev

- name: Clone OctoPrint (developer mode)
  become: true
  become_user: '{{ octoprint_user }}'
  ansible.builtin.git:
    repo: '{{ octoprint_repo }}'
    dest: '{{ octoprint_repo_dir }}'
    version: '{{ octoprint_git_tag }}'
  tags:
    - setup
    - system-update
    - octoprint
  when: octoprint_plugin_dev

- name: Install OctoPrint (developer mode)
  become: true
  become_user: '{{ octoprint_user }}'
  ansible.builtin.pip:
    name: '.[develop,plugins]'
    virtualenv: '{{ octoprint_venv }}'
    editable: true
    chdir: '{{ octoprint_repo_dir }}'
  tags:
    - setup
    - system-update
    - octoprint
  when: octoprint_plugin_dev

- name: Clone OctoPrint plugin (developer mode)
  become: true
  become_user: '{{ octoprint_user }}'
  ansible.builtin.git:
    repo: '{{ octoprint_printnanny_plugin_repo }}'
    dest: '{{ octoprint_printnanny_plugin_dir }}'
    version: '{{ octoprint_printnanny_plugin_version }}'
    accept_hostkey: true
  tags:
    - setup
    - system-update
    - octoprint
  when: octoprint_plugin_dev

- name: Add git-ssh remote (developer mode)
  become: true
  become_user: '{{ octoprint_user }}'
  ansible.builtin.git:
    repo: '{{ octoprint_plugin_git_repo }}'
    dest: '{{ octoprint_printnanny_plugin_dir }}'
    version: '{{ octoprint_printnanny_plugin_version }}'
    accept_hostkey: true
    remote: gitssh
    update: false
  tags:
    - setup
    - system-update
    - octoprint
  when: octoprint_plugin_dev

- name: Install OctoPrint plugin (developer mode)
  become: true
  become_user: '{{ octoprint_user }}'
  ansible.builtin.pip:
    name: '.'
    virtualenv: '{{ octoprint_venv }}'
    editable: true
    chdir: '{{ octoprint_printnanny_plugin_dir }}'
  tags:
    - setup
    - system-update
    - octoprint
  when: octoprint_plugin_dev
