---
- name: Assert printnanny_cmd is defined
  ansible.builtin.assert:
    that:
      - printnanny_cmd is defined
- name: Debug printnanny_cmd
  ansible.builtin.debug:
    var: printnanny_cmd
- name: Update stream ansible facts
  ansible.builtin.set_fact:
    janus_cloud_api_domain: '{{ printnanny_cmd.stream.api_domain }}'
    janus_cloud_rtp_domain: '{{ printnanny_cmd.stream.rtp_domain }}'
    janus_cloud_rtp_port: '{{ printnanny_cmd.stream.rtp_port }}'
    cacheable: true

- name: Run monitor tasks
  ansible.builtin.include_role:
    name: bitsyai.printnanny.install
    tasks_from: monitor
- name: Start monitor service
  ansible.builtin.systemd:
    name: printnanny-monitor
    state: restarted
