---
# defaults file for octoprint

octoprint_user: pi
octoprint_version: 'octoprint>1.7,<2'
octoprint_dir: '/home/{{ octoprint_user }}/.octoprint'
octoprint_venv: '{{ octoprint_dir }}/venv'
octoprint_config: '{{ octoprint_dir }}/config.yml'
octoprint_printnanny_plugin_version: 'git+https://github.com/bitsy-ai/octoprint-nanny-plugin.git@0.8.0'
octoprint_host: 127.0.0.1
octoprint_port: 5000

# TODO replace with Print Nanny Network ca-signed cert
octoprint_ssl_cert: '/etc/ssl/certs/ssl-cert-snakeoil.pem'
octoprint_ssl_key: '/etc/ssl/private/ssl-cert-snakeoil.key'
octoprint_ssl_protocols: 'TLSv1 TLSv1.1 TLSv1.2'
octoprint_ssl_ciphers: 'HIGH:!aNULL:!MD5;'

octoprint_log_dir: '/var/log/octoprint'
octoprint_watched_dir: '/var/run/octoprint/watched'
