---
# defaults file for octoprint

octoprint_user: pi
octoprint_pip_version: 'octoprint>1.7,<2'
# dirs
octoprint_dir: '/home/{{ octoprint_user }}/.octoprint'
octoprint_log_dir: '/var/log/octoprint'
octoprint_watched_dir: '/var/run/octoprint/watched'
octoprint_venv: '{{ octoprint_dir }}/venv'
octoprint_config: '{{ octoprint_dir }}/config.yml'

# plugin
octoprint_git_version: 1.7.3
octoprint_repo: https://github.com/OctoPrint/OctoPrint
octoprint_repo_dir: '/home/{{ octoprint_user }}/octoprint-src'
octoprint_printnanny_plugin_repo: https://github.com/bitsy-ai/octoprint-nanny-plugin.git
octoprint_printnanny_plugin_version: 0.9.1
octoprint_printnanny_pip_install: 'git+{{ octoprint_printnanny_plugin_repo }}@{{ octoprint_printnanny_plugin_version }}'
# used to configure git in developer mode
octoprint_plugin_git_email: 'leigh@bitsy.ai'
octoprint_plugin_git_name: 'Leigh Johnson'
# install plugin in editable mode
octoprint_printnanny_plugin_dir: '/home/{{ octoprint_user }}/octoprint-nanny-plugin'
octoprint_printnanny_plugin_dev: false
# octoprint defaults
octoprint_host: 127.0.0.1
octoprint_port: 5000

# TODO replace with Print Nanny Network ca-signed cert
octoprint_ssl_cert: '/etc/ssl/certs/ssl-cert-snakeoil.pem'
octoprint_ssl_key: '/etc/ssl/private/ssl-cert-snakeoil.key'
octoprint_ssl_protocols: 'TLSv1 TLSv1.1 TLSv1.2'
octoprint_ssl_ciphers: 'HIGH:!aNULL:!MD5'
