---
# defaults file for octoprint

octoprint_user: pi
octoprint_version: 'octoprint>1.7,<2'
octoprint_dir: "/home/{{ octoprint_user }}/.octoprint"
octoprint_venv: "{{ octoprint_dir }}/venv"
octoprint_config: "{{ octoprint_dir }}/config.yml"
octoprint_printnanny_plugin_version: 'git+https://github.com/bitsy-ai/octoprint-nanny-plugin.git@0.8.0'
octoprint_host: 127.0.0.1
octoprint_port: 5000
