---
# defaults file for octoprint

octoprint_user: octoprint
# dirs
octoprint_dir: '/home/{{ octoprint_user }}/.octoprint'
octoprint_log_dir: '/var/log/octoprint'
octoprint_watched_dir: '/var/run/octoprint/watched'
octoprint_venv: '{{ octoprint_dir }}/venv'
octoprint_config: '{{ octoprint_dir }}/config.yaml'

# plugin
octoprint_git_tag: 1.8.0rc5
octoprint_version: 'OctoPrint=={{ octoprint_git_tag }}'
octoprint_repo: https://github.com/OctoPrint/OctoPrint
octoprint_repo_dir: '/home/{{ octoprint_user }}/octoprint-src'
octoprint_printnanny_plugin_repo: https://github.com/bitsy-ai/octoprint-nanny-plugin.git
octoprint_printnanny_plugin_version: 0.10.0rc2
octoprint_printnanny_pip_install: 'octoprint-nanny=={{ octoprint_printnanny_plugin_version }}'
# used to configure git in developer mode
octoprint_plugin_git_repo: git@github.com:bitsy-ai/octoprint-nanny-plugin.git
octoprint_plugin_git_keys: https://github.com/leigh-johnson.keys
octoprint_plugin_git_email: 'leigh@bitsy.ai'
octoprint_plugin_git_name: 'Leigh Johnson'
# install plugin in editable mode
octoprint_printnanny_plugin_dir: '/home/{{ octoprint_user }}/octoprint-nanny-plugin'
octoprint_plugin_dev: false
# octoprint defaults
octoprint_host: 127.0.0.1
octoprint_port: 5000

# used to set nginx's client_max_body_size for /octoprint/ location
octoprint_file_upload_max: 1G

# TODO replace with PrintNanny Network ca-signed cert
octoprint_ssl_cert: '/etc/ssl/certs/ssl-cert-snakeoil.pem'
octoprint_ssl_key: '/etc/ssl/private/ssl-cert-snakeoil.key'
octoprint_ssl_protocols: 'TLSv1 TLSv1.1 TLSv1.2'
octoprint_ssl_ciphers: 'HIGH:!aNULL:!MD5'

printnanny_install_dir: '/opt/printnanny'
printnanny_ansible_dir: "{{ printnanny_install_dir }}/ansible"
updater_venv: '{{ printnanny_ansible_dir }}/venv'
