---
# tasks file for grafana
- name: Install apt dependencies
  become: true
  ansible.builtin.apt:
    name:
      - python3-dev
      - python3-pip
      - python3-venv
      # required by ansible.builtin.package_facts
      - python3-apt
- name: Gather package facts
  package_facts:
    manager: apt

- name: Download grafana-agent package
  ansible.builtin.get_url:
    url: "{{ grafana_agent_deb_url }}"
    dest: "/tmp/{{ grafana_agent_deb_file }}"
  when: (ansible_facts.packages.grafana_agent is not defined) or
    (ansible_facts.packages.grafana_agent[0].version != grafana_agent_version)

- name: Install grafana-agent
  become: true
  ansible.builtin.apt:
    deb: "/tmp/{{ grafana_agent_deb_file }}"
  when: (ansible_facts.packages.grafana_agent is not defined) or
    (ansible_facts.packages.grafana_agent[0].version != grafana_agent_version)

- name: Clean up honeytail package
  ansible.builtin.file:
    name: "/tmp/{{ grafana_agent_deb_file  }}"
    state: absent
