---
# defaults file for ansible_pull

updater_auto_playbooks:
  - bitsyai.rpi.auto_update

updater_manual_playbooks:
  - bitsyai.rpi.manual_update

updater_collection_url: git+https://github.com/bitsy-ai/ansible-collection-rpi.git,main

updater_collection: bitsyai.rpi
updater_app_name: bitsy

updater_auto_service: '{{ updater_app_name }}-cli-update'
updater_manual_service: '{{ updater_app_name }}-system-update'

updater_user: ansible
updater_venv: '/home/{{ updater_user }}/venv'

ansible_updater_version: 'ansible>4,<5'
ansible_collection_updater: ansible-updater

updater_tmpfs: '/var/run/{{ updater_app_name }}'
ansible_lockfile: '/var/run/{{ updater_app_name }}/ansible.lock'

ansible_hosts_file: /etc/ansible/hosts
ansible_config:
  fact_caching_timeout: 86400
  fact_caching: jsonfile
  fact_caching_connection: /etc/ansible/facts.json

updater_timer:
  # update every hour
  OnUnitInactiveSec: 3600
  # offset by 60 seconds of jitter
  RandomizedDelaySec: 60
  # always update 2 minutes after booting
  OnStartupSec: 120

updaters:
  # each entry is a map {} with keys:
  # name: ""
  # playbooks: []
  # service_template: ""
  # service_enabled: ""
  # service_state: ""
  # user: ""
  # add printnanny-updaters here
  - name: "printnanny-update-system"
    app_name: printnanny
    user: printnanny
    playbooks:
      - "bitsyai.rpi.printnanny.update.system"
    service_template: "updater.service.j2"
    service_enabled: false
    state: started
  - name: "printnanny-update-janus"
    app_name: printnanny
    user: printnanny
    playbooks:
      - "bitsyai.rpi.printnanny.update.janus"
    service_template: "updater.service.j2"
    service_enabled: false
    state: started
  - name: "printnanny-update-cli"
    app_name: printnanny
    user: printnanny
    playbooks:
      - "bitsyai.rpi.printnanny.update.cli"
    service_template: "updater.service.j2"
    service_enabled: false
    state: started
