---
updater_collection_url: git+https://github.com/bitsy-ai/ansible-collection-rpi.git,main

updater_collection: bitsyai.rpi
updater_app_name: bitsy

updater_user: ansible
updater_venv: '/home/{{ updater_user }}/venv'

ansible_updater_version: 'ansible>4,<5'
ansible_collection_updater: ansible-updater

updater_tmpfs: '/var/run/{{ updater_app_name }}'
ansible_lockfile: '/var/run/{{ updater_app_name }}/ansible.lock'

ansible_hosts_file: /etc/ansible/hosts
ansible_config:
  fact_caching_timeout: 86400
  fact_caching: jsonfile
  fact_caching_connection: /etc/ansible/facts.json

updaters: []

# ara configuration (optional)
# https://ara.readthedocs.io/

ara_enabled: false
ara_version: 'ara>1.5,<1.6'

# ara configuration values: https://ara.readthedocs.io/en/latest/ansible-plugins-and-use-cases.html
ara_api_client: 'http'
ara_api_server: 'https://ara.print-nanny.com'
ara_api_timeout: 15
ara_callback_threads: 4
ara_ignored_arguments: vault_password_files
ara_default_labels: deploy
ara_argument_labels: check,subset,tags
