---
# defaults file for ansible_pull

app_path: /opt/bitsy

updater:
  name: 'rpi-updater'
  user: ansible
  ansible_version: 'ansible>4,<5'
  ansible_venv: "{{ app_path }}/ansible/venv"
  ansible_hosts_file: /etc/ansible/hosts
  ansible_lockfile: /var/run/ansible/ansible.lock
  timer:
    OnUnitInactiveSec: 3600 # update every hour
    RandomizedDelaySec: 60 # offset by 60 seconds of jitter
    OnStartupSec: 120 # always update 2 minutes after booting

  ansible_config:
    fact_caching_timeout: 86400
    fact_caching: jsonfile
    fact_caching_connection: /etc/ansible/facts.json

updater_collection:
  name: 'rpi-updater'
  src: 'bitsyai.rpi.automatic_updates'
  url: 'git+https://github.com/bitsy-ai/ansible-collection-rpi.git,main'
