---
# defaults file for ansible_pull

auto_update_playbook: bitsyai.rpi.auto_update
updater_collection_url: git+https://github.com/bitsy-ai/ansible-collection-rpi.git,main

updater_collection: bitsyai.rpi
updater_app_name: bitsy

auto_update_service: '{{ updater_app_name }}-updater'

updater_user: ansible
updater_venv: '/home/{{ updater_user }}/venv'

ansible_updater_version: 'ansible>4,<5'
ansible_collection_updater: ansible-updater

updater_tmpfs: '/var/run/{{ updater_app_name }}'
ansible_lockfile: '/var/run/{{ updater_app_name }}/ansible.lock'

ansible_hosts_file: /etc/ansible/hosts
ansible_config:
  fact_caching_timeout: 86400
  fact_caching: jsonfile
  fact_caching_connection: /etc/ansible/facts.json

updater_timer:
  # update every hour
  OnUnitInactiveSec: 3600
  # offset by 60 seconds of jitter
  RandomizedDelaySec: 60
  # always update 2 minutes after booting
  OnStartupSec: 120
