---
# defaults file for ansible_pull

automatic_update_playbook: bitsyai.rpi.upgrade

auto_upgrade_service: bitsy-updater
ansible_update_service: ansible-updater

updater_collection: bitsyai.rpi
updater_user: ansible
updater_ansible_version: 'ansible>4,<5'

ansible_hosts_file: /etc/ansible/hosts
ansible_tmpfs: /var/run/ansible
ansible_lockfile: /var/run/ansible/ansible.lock

ansible_config:
  fact_caching_timeout: 86400
  fact_caching: jsonfile
  fact_caching_connection: /etc/ansible/facts.json

updater_timer:
  # update every hour
  OnUnitInactiveSec: 3600
  # offset by 60 seconds of jitter
  RandomizedDelaySec: 60
  # always update 2 minutes after booting
  OnStartupSec: 120
