---
metadata_apps:
    - janus
    - www
    - env
    - mqtt

##
# updater_ vars
##

updater_app_name: printnanny
updater_playbooks:
    - bitsyai.rpi.printnanny.system

printnanny_release_channel: 'main'
updater_collection_url: 'git+https://github.com/bitsy-ai/ansible-collection-rpi.git,{{ printnanny_release_channel }}'

updater_venv: '{{ printnanny_ansible_dir }}/venv'

jinja2_version: 'jinja2>=2.11'
ansible_updater_version: 'ansible-core>2.12,<2.13'
ansible_collection_updater: ansible-updater
updater_tmpfs: '/var/run/{{ updater_app_name }}'
ansible_lockfile: '/var/run/{{ updater_app_name }}/ansible.lock'

ansible_hosts_file: /etc/ansible/hosts
ansible_config:
    fact_caching_timeout: 86400
    fact_caching: jsonfile
    fact_caching_connection: /etc/ansible/facts.json

## janus vars
janus_conf_dir: /etc/janus
janus_admin_secret_file: '{{ janus_conf_dir }}/janus_admin_secret'
janus_token_file: '{{ janus_conf_dir }}/janus_token'
janus_admin_secret: "{{ lookup('password', janus_admin_secret_file, length=32 ) }}"
janus_token: "{{ lookup('password', janus_token_file, length=32 ) }}"
