---
##
# updater_ vars
##

printnanny_collection_version: 1.5.7
printnanny_edition: octoprint_desktop
updater_app_name: printnanny
updater_playbooks:
  - 'bitsyai.printnanny.images.{{ printnanny_edition }}'

printnanny_release_channel: 'main'
updater_collection_url: 'git+https://github.com/bitsy-ai/ansible-collection-printnanny.git,{{ printnanny_release_channel }}'

update_user: ansible
updater_venv: '{{ printnanny_ansible_dir }}/venv'

jinja2_version: 'jinja2>=2.11'
ansible_updater_version: 'ansible-core>2.12,<2.13'
ansible_collection_updater: ansible-updater
updater_tmpfs: '/var/run/{{ updater_app_name }}'
ansible_lockfile: '/var/run/{{ updater_app_name }}/ansible.lock'

ansible_hosts_file: /etc/ansible/hosts
ansible_config:
  fact_caching_timeout: 86400
  fact_caching: jsonfile
  fact_caching_connection: /opt/printnanny/ansible/facts.json

## janus vars
janus_local_enabled: false
local_remote_enabled: true
janus_conf_dir: /etc/janus
janus_admin_secret_file: '{{ janus_conf_dir }}/janus_admin_secret'
janus_token_file: '{{ janus_conf_dir }}/janus_token'
janus_admin_secret: "{{ lookup('password', janus_admin_secret_file, length=32 ) }}"
janus_token: "{{ lookup('password', janus_token_file, length=32 ) }}"
janus_install_dir: /opt/janus

janus_conf:
  janus:
    plugins_folder: "{{ janus_install_dir }}/lib/janus/plugins"
    transports_folder: "{{ janus_install_dir }}/lib/janus/transports"
    events_folder: "{{ janus_install_dir }}/lib/janus/events"
    loggers_folder: "{{ janus_install_dir }}/lib/janus/loggers"
    log_to_stdout: true
    debug_level: 7
    pid_file: "/var/run/janus.pid"
    session_timeout: 60
    candidates_timeout: 45
    reclaim_session_timeout: 0
    no_webrtc_encryption: false
    ignore_unreachable_ice_server: true
    janus.transport.http:
    admin_base_path: "/admin"
    admin_http_port: 7088
    admin_https_port: 7089
    admin_http: true
    admin_https: false
    base_path: "/janus"
    https: false
    https_port: 8089
    http: true
    http_port: 8088
  janus.transport.http:
    admin_base_path: "/admin"
    admin_http_port: 7088
    admin_https_port: 7089
    admin_http: true
    admin_https: false
    base_path: "/janus"
    https: false
    https_port: 8089
    http: true
    http_port: 8088
