---
metadata_apps:
    - janus
    - www
    - env
    - mqtt

##
# printnanny_ vars
##
printnanny_profile: default
printnanny_loglevel: info

printnanny_api_url: https://print-nanny.com
printnanny_service_dir: /etc/systemd/printnanny.d
printnanny_runtime_dir: /var/run/printnanny
printnanny_env: '{{ printnanny_runtime_dir }}/env'
printnanny_env_sh: '{{ printnanny_runtime_dir }}/env.sh'

printnanny_install_dir: '/opt/printnanny'
printnanny_profile_dir: '{{ printnanny_install_dir }}/{{ printnanny_profile }}'
printnanny_cacerts: '{{ printnanny_profile_dir }}/ca-certificates'
printnanny_data_dir: '{{ printnanny_profile_dir }}/data'
printnanny_keys_dir: '{{ printnanny_profile_dir }}/keys'
printnanny_ec_private_key: '{{ printnanny_keys_dir }}/ec_private.pem'
printnanny_ec_public_key: '{{ printnanny_keys_dir }}/ec_public.pem'

printnanny_config_toml: '{{ printnanny_profile_dir }}/PrintNanny.toml'
printnanny_backups_dir: "{{ printnanny_profile_dir }}/backups"
printnanny_ansible_dir: "{{ printnanny_install_dir }}/ansible"

printnanny_www_dir: '{{ printnanny_profile_dir }}/www'
printnanny_www_secret_file: '{{ printnanny_www_dir }}/key'
printnanny_www_templates_dir: '{{ printnanny_www_dir }}/templates'
printnanny_www_address: "0.0.0.0"
printnanny_www_port: 9001
printnanny_www_log_level: "normal"

ansible_facts_path: /etc/ansible/facts.d
printnanny_device_fact: /etc/ansible/facts.d/device.fact
printnanny_license_fact: /etc/ansible/facts.d/license.fact
printnanny_janus_fact: /etc/ansible/facts.d/janus.fact

printnanny_cli_version: 0.12.16
printnanny_cli_repo: 'https://github.com/bitsy-ai/printnanny-cli'
printnanny_cli_url: '{{ printnanny_cli_repo }}/releases/download/v{{ printnanny_cli_version }}/printnanny-{{ ansible_architecture }}-unknown-linux-gnu.tar.gz'
printnanny_www_templates_url: '{{ printnanny_cli_repo }}/releases/download/v{{ printnanny_cli_version }}/printnanny-www-templates.tar.gz'
printnanny_ansible_version: 'ansible>4,<5'
printnanny_update_schedule: '*/15 * * * *'
printnanny_user: printnanny
printnanny_group: printnanny

janus_ssl_key_size: 2048
janus_ssl_key_type: DSA
janus_ssl_dir: '{{ janus_install_dir }}/ssl'
janus_ssl_crt_dir: '{{ janus_install_dir }}/ssl/crt'
janus_ssl_key_dir: '{{ janus_install_dir }}/ssl/private'
janus_ssl_csr_dir: '{{ janus_install_dir }}/ssl/csr'
janus_ssl_cert: '{{ janus_ssl_crt_dir}}/janus.crt'
janus_ssl_key: '{{ janus_ssl_key_dir}}/janus.pem'
janus_ssl_csr: '{{ janus_ssl_csr_dir }}/janus.csr'

janus_ssl_country_name: 'US'
janus_ssl_email_address: support@print-nanny.com
janus_ssl_organization_name: 'Bitsy AI Labs, LLC'
printnanny_variant: desktop

##
# libcamera vars
##
libcamera_repo: https://git.libcamera.org/libcamera/libcamera.git
libcamera_version: 7ea52d2b586144fdc033a3ffc1c4a4bbb99b5440
libcamera_apps_version: 14e32b75ebba9a06c030ef7cb0f2f14cdb74a586
libcamera_apps_repo: https://github.com/raspberrypi/libcamera-apps.git


##
# gcp_ vars
##
gcp_lts_ca_primary: https://pki.goog/gtsltsr/gtsltsr.crt
gcp_lts_ca_backup: https://pki.goog/gsr4/GSR4.crt

##
# updater_ vars
##

updater_app_name: printnanny
updater_playbooks:
    - bitsyai.rpi.printnanny.update.system

updater_release_channel: '{{ printnanny.release_channel | default("main") }}'
updater_collection_url: 'git+https://github.com/bitsy-ai/ansible-collection-rpi.git,{{ updater_release_channel }}'

updater_venv: '{{ printnanny_ansible_dir }}/venv'

ansible_updater_version: 'ansible-core>2.11,<2.12'
ansible_collection_updater: ansible-updater
updater_tmpfs: '/var/run/{{ updater_app_name }}'
ansible_lockfile: '/var/run/{{ updater_app_name }}/ansible.lock'

ansible_hosts_file: /etc/ansible/hosts
ansible_config:
    fact_caching_timeout: 86400
    fact_caching: jsonfile
    fact_caching_connection: /etc/ansible/facts.json

##
# ara_ vars
##
# ara configuration (optional)
# https://ara.readthedocs.io/

ara_enabled: true
ara_version: 'ara>1.5,<1.6'

# ara configuration values: https://ara.readthedocs.io/en/latest/ansible-plugins-and-use-cases.html
ara_api_client: http
ara_api_server: https://ara.print-nanny.com
ara_api_timeout: 15
ara_callback_threads: 4
ara_ignored_arguments: vault_password_files
ara_default_labels: 'channel:{{updater_release_channel}}'
ara_argument_labels: check,subset,tags

##
# gstreamer vars
##

cam_rtp_port: 5104
gstreamer_num_buffers: 3
gstreamer_config_interval: 1
gstreamer_video_src: 'v4l2src'

# TODO select from output of:
# libcamera-vid --list-camera
gstreamer_video_w: 1280
gstreamer_video_h: 720
gstreamer_rtp_host: "127.0.0.1"

##
# nnstreamer vars
##

nn_threshold: 50
nn_rtp_port: 5105
nn_rtp_service: printnanny-gst
nn_capture_framerate: 30

nn_tensor_height: 320
nn_tensor_width: 320

nn_framework: tensorflow-lite

nn_base_url: https://cdn.print-nanny.com/ml/print3d_20201101015829
nn_model_url: '{{ nn_base_url }}/model.tflite'
nn_label_url: '{{ nn_base_url }}/dict.txt'
nn_metadata_url: '{{ nn_base_url }}/tflite_metadata.json'

nn_install_dir: '{{printnanny_profile_dir}}/nn'

nn_model_file: '{{ nn_install_dir }}/model.tflite'
nn_label_file: '{{ nn_install_dir }}/dict.txt'
nn_metadata_file: '{{ nn_install_dir }}/tflite_metadata.json'

##
# honeycomb vars
##
honeycomb_dataset: 'printnanny_os'
honeycomb_api_key: '22ffab0ec6af32b2be565bc831555e44'

##
# janus vars
##
janus_user: janus
janus_install_dir: /opt/janus
janus_admin_url: 'http://localhost:{{ janus_conf["janus.transport.http"]["admin_http_port"] }}{{ janus_conf["janus.transport.http"]["admin_base_path"] }}'
janus_url: 'http://localhost:{{ janus_conf["janus.transport.http"]["http_port"] }}{{ janus_conf["janus.transport.http"]["base_path"] }}'

janus_unit_extra: |
    EnvironmentFile=-{{ printnanny_env }}
    ExecStartPost=printnanny janus-admin add-token

janus_conf:
    janus:
        plugins_folder: "{{ janus_install_dir }}/lib/janus/plugins"
        transports_folder: "{{ janus_install_dir }}/lib/janus/transports"
        events_folder: "{{ janus_install_dir }}/lib/janus/events"
        loggers_folder: "{{ janus_install_dir }}/lib/janus/loggers"
        log_to_stdout: true
        debug_level: 7
        pid_file: "/var/run/janus.pid"
        session_timeout: 60
        candidates_timeout: 45
        reclaim_session_timeout: 0
        no_webrtc_encryption: false
        ignore_unreachable_ice_server: true
    janus.transport.http:
        admin_base_path: "/admin"
        admin_http_port: 7088
        admin_https_port: 7089
        admin_http: true
        admin_https: false
        base_path: "/janus"
        https: false
        https_port: 8089
        http: true
        http_port: 8088
