---
- hosts: printnanny
  gather_facts: true
  roles:
    - bitsyai.rpi.common
    - bitsyai.rpi.printnanny
    - bitsyai.rpi.janus
  tasks:
    - name: Clean and minimize image
      include_role:
        name: bitsyai.rpi.common
        tasks_from: clean_image
