---
- hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'update janus'
    ara_playbook_labels:
      - update
      - printnanny
      - janus
      - system
  tasks:
    - name: Include roles/printnanny/defaults
      include_vars: ../../../roles/printnanny/defaults/main.yml
    - name: Include janus role
      include_role:
        name: bitsyai.printnanny.janus
