---
- hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'render printnanny metadata'
    ara_playbook_labels:
      - printnanny
      - env
      - metadata
  tasks:
    - name: Print gathered facts
      include_role:
        name: bitsyai.rpi.printnanny
        tasks_from: metadata/debug.yml
    - name: Include handlers
      include: ../roles/printnanny/handlers/main.yml
    - name: Include profile-specific roles/printnanny/vars
      include_vars: '../../roles/printnanny/vars/{{ printnanny_profile }}.yml'
    - name: Print gathered facts
      include_role:
        name: bitsyai.rpi.printnanny
        tasks_from: metadata/main.yml
