---
- hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'render printnanny metadata for env app'
    ara_playbook_labels:
      - printnanny
      - env
      - metadata
      - env
  roles:
    - bitsyai.rpi.printnanny
  tasks:
    - name: Update Print Nanny metadata
      include_role:
        name: bitsyai.rpi.metadata
        vars_from: '{{ printnanny_profile }}.yml'
      tags:
        - metadata
