---
- hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'update printnanny system'
    ara_playbook_labels:
      - update
      - printnanny
      - system
  roles:
    - bitsyai.rpi.common
    - bitsyai.rpi.metadata
  tasks:

    - name: Include printnanny role (custom profile)
      include_role:
        name: bitsyai.rpi.printnanny
        public: true
        vars_from: '{{ printnanny_profile }}.yml'
      when: printnanny_profile is defined
    - name: Include printnanny role (custom profile)
      include_role:
        name: bitsyai.rpi.printnanny
        public: true
      when: not printnanny_profile is defined
    - name: Install Janus
      include_role:
        name: bitsyai.rpi.janus
      vars:
        janus_ssl_cert: '{{ printnanny_ssl_cert }}'
        janus_ssl_key: '{{ printnanny_ssl_key }}'
