---
- hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'update printnanny system'
    ara_playbook_labels:
      - update
      - printnanny
      - system
  roles:
    - bitsyai.rpi.common
    - bitsyai.rpi.metadata
  vars_files:
    - ../../roles/metadata/vars/{{ printnanny_profile|default("default", true) }}.yml
    - ../../roles/printnanny/vars/{{ printnanny_edition|default("octoprint_desktop", true) }}.yml
  tasks:
    - name: Include printnanny role (custom profile)
      include_role:
        name: bitsyai.rpi.printnanny
        public: true
    - name: Install OctoPrint
      include_role:
        name: bitsyai.rpi.octoprint
        vars_from: '../../../roles/metadata/vars/{{ printnanny_edition|default("octoprint_desktop", true) }}.yml'
      when: (printnanny_edition|default("octoprint_desktop", true) == "octoprint_desktop" or
        printnanny_edition|default("octoprint_lite", true) == "octoprint_lite")
    - name: Install Janus
      include_role:
        name: bitsyai.rpi.janus
      vars:
        janus_ssl_cert: '{{ printnanny_ssl_cert }}'
        janus_ssl_key: '{{ printnanny_ssl_key }}'
