---
- hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'update printnanny system'
    ara_playbook_labels:
      - update
      - printnanny
      - system
    nginx_start: false
    nginx_setup_license: false
    nginx_logrotate_conf_enable: false
    nginx_modules:
      - njs
    nginx_config_debug_output: true
  roles:
    - nginxinc.nginx_core.nginx
    - nginxinc.nginx_core.nginx_config
    - bitsyai.rpi.common
    - bitsyai.rpi.metadata
  tasks:
    - name: Include PrintNanny Profile Vars
      include_vars: ../../roles/metadata/vars/{{ printnanny_profile|default("default", true) }}.yml
    - name: Include PrintNanny Edition vars
      include_vars: ../../roles/printnanny/vars/{{ printnanny_edition|default("octoprint_desktop", true) }}.yml
    - name: Install Print Nanny
      include_role:
        name: bitsyai.rpi.printnanny
        public: true
    - name: Install OctoPrint
      include_role:
        name: bitsyai.rpi.octoprint
      when: (printnanny_edition|default("octoprint_desktop", true) == "octoprint_desktop" or
        printnanny_edition|default("octoprint_lite", true) == "octoprint_lite")
    - name: Install Janus
      include_role:
        name: bitsyai.rpi.janus
      vars:
        janus_ssl_cert: '{{ printnanny_ssl_cert }}'
        janus_ssl_key: '{{ printnanny_ssl_key }}'
