---

##
# nginx vars
##

nginx_proxy_busy_buffers_size: '512k'
nginx_proxy_buffers_num: 4
nginx_buffer_size: '256k'

##
##
# printnanny_ vars
##
printnanny_profile: default
printnanny_loglevel: info

printnanny_api_url: https://print-nanny.com
printnanny_service_dir: /etc/systemd/printnanny.d
printnanny_runtime_dir: /var/run/printnanny
printnanny_env: '{{ printnanny_runtime_dir }}/env'
printnanny_env_sh: '{{ printnanny_runtime_dir }}/env.sh'

printnanny_install_dir: '/opt/printnanny'
printnanny_profile_dir: '{{ printnanny_install_dir }}/profiles/{{ printnanny_profile }}'
printnanny_cmd_dir: '{{ printnanny_install_dir }}/cmd'
printnanny_cmd_pending_dir: '{{ printnanny_cmd_dir }}/pending'
printnanny_cmd_done_dir: '{{ printnanny_cmd_dir }}/done'
printnanny_cmd_error_dir: '{{ printnanny_cmd_dir }}/error'


printnanny_cacerts: '{{ printnanny_profile_dir }}/ca-certificates'
printnanny_data_dir: '{{ printnanny_profile_dir }}/data'
printnanny_keys_dir: '{{ printnanny_profile_dir }}/keys'
printnanny_ec_private_key: '{{ printnanny_keys_dir }}/ec_private.pem'
printnanny_ec_public_key: '{{ printnanny_keys_dir }}/ec_public.pem'
printnanny_ec_fingerprint_md5: '{{ printnanny_keys_dir }}/ec_fingerprint.md5'

printnanny_config_toml: '{{ printnanny_profile_dir }}/PrintNanny.toml'
printnanny_backups_dir: "{{ printnanny_profile_dir }}/backups"
printnanny_ansible_dir: "{{ printnanny_install_dir }}/ansible"

printnanny_www_dir: '{{ printnanny_install_dir }}/www'
printnanny_www_secret_file: '{{ printnanny_www_dir }}/key'
printnanny_www_templates_dir: '{{ printnanny_www_dir }}/templates'
printnanny_www_address: "127.0.0.1"
printnanny_www_port: 9001
printnanny_www_log_level: "normal"

ansible_facts_path: /etc/ansible/facts.d
printnanny_device_fact: /etc/ansible/facts.d/device.fact
printnanny_license_fact: /etc/ansible/facts.d/license.fact
printnanny_janus_fact: /etc/ansible/facts.d/janus.fact

printnanny_cli_version: 0.16.10
printnanny_cli_repo: 'https://github.com/bitsy-ai/printnanny-cli'
printnanny_cli_url: '{{ printnanny_cli_repo }}/releases/download/v{{ printnanny_cli_version }}/printnanny-{{ ansible_architecture }}-unknown-linux-gnu.tar.gz'
printnanny_www_templates_url: '{{ printnanny_cli_repo }}/releases/download/v{{ printnanny_cli_version }}/printnanny-www-templates.tar.gz'
printnanny_update_schedule: '*/15 * * * *'
printnanny_user: printnanny
printnanny_group: printnanny
printnanny_groups:
  - ssl-cert
printnanny_release_channel: main

printnanny_ssl_key_size: 2048
printnanny_ssl_key_type: DSA

# TODO replace with Print Nanny Network ca-signed cert
printnanny_ssl_cert: '/etc/ssl/certs/ssl-cert-snakeoil.pem'
printnanny_ssl_key: '/etc/ssl/private/ssl-cert-snakeoil.key'
printnanny_ssl_protocols: 'TLSv1 TLSv1.1 TLSv1.2'
printnanny_ssl_ciphers: 'HIGH:!aNULL:!MD5'
printnanny_ssl_country_name: 'US'
printnanny_ssl_email_address: support@print-nanny.com
printnanny_ssl_organization_name: 'Bitsy AI Labs, LLC'
printnanny_edition: octoprint_desktop

##
# log dirs
##
printnanny_log_dir: "/var/log/printnanny"
printnanny_update_log: '{{ printnanny_log_dir }}/printnanny_update.log'
printnanny_www_log: '{{ printnanny_log_dir }}/printnanny_www.log'
printnanny_mqtt_log: '{{ printnanny_log_dir }}/printnanny_mqtt.log'
printnanny_webrtc_log: '{{ printnanny_log_dir }}/printnanny_webrtc.log'
printnanny_cam_log: '{{ printnanny_log_dir }}/printnanny_cam.log'
printnanny_nginx_log: '{{ printnanny_log_dir }}/printnanny_nginx.log'

##
# libcamera vars
##
libcamera_repo: https://git.libcamera.org/libcamera/libcamera.git
libcamera_version: 7ea52d2b586144fdc033a3ffc1c4a4bbb99b5440
libcamera_apps_version: 14e32b75ebba9a06c030ef7cb0f2f14cdb74a586
libcamera_apps_repo: https://github.com/raspberrypi/libcamera-apps.git
libcamera_installed_version: null
libcamera_build_source: false

##
# gcp_ vars
##
gcp_lts_ca_primary: https://pki.goog/gtsltsr/gtsltsr.crt
gcp_lts_ca_backup: https://pki.goog/gsr4/GSR4.crt

##
# ara_ vars
##
# ara configuration (optional)
# https://ara.readthedocs.io/

ara_enabled: true
ara_version: 'ara>1.5,<1.6'

# ara configuration values: https://ara.readthedocs.io/en/latest/ansible-plugins-and-use-cases.html
ara_api_client: http
ara_api_server: https://ara.print-nanny.com
ara_api_timeout: 15
ara_callback_threads: 4
ara_ignored_arguments: vault_password_files
ara_default_labels: 'channel:{{ printnanny_release_channel }}'
ara_argument_labels: check,subset,tags

##
# gstreamer vars
##

cam_rtp_port: 5104
gstreamer_num_buffers: 3
gstreamer_config_interval: 1
gstreamer_video_src: 'v4l2src'

# TODO select from output of:
# libcamera-vid --list-camera
gstreamer_video_w: 1280
gstreamer_video_h: 720
gstreamer_rtp_host: "127.0.0.1"

##
# nnstreamer vars
##

nn_threshold: 50
nn_rtp_port: 5105
nn_rtp_service: printnanny-monitor
nn_capture_framerate: 30

nn_tensor_height: 320
nn_tensor_width: 320

nn_framework: tensorflow-lite

nn_base_url: https://cdn.print-nanny.com/ml/print3d_20201101015829
nn_model_url: '{{ nn_base_url }}/model.tflite'
nn_label_url: '{{ nn_base_url }}/dict.txt'
nn_metadata_url: '{{ nn_base_url }}/tflite_metadata.json'

nn_install_dir: '{{ printnanny_install_dir }}/nn'

nn_model_file: '{{ nn_install_dir }}/model.tflite'
nn_label_file: '{{ nn_install_dir }}/dict.txt'
nn_metadata_file: '{{ nn_install_dir }}/tflite_metadata.json'

##
# honeycomb vars
##
honeycomb_dataset: 'printnanny_os'
honeycomb_api_key: '22ffab0ec6af32b2be565bc831555e44'

##
# janus vars
##
janus_api_domain: janus.beta.print-nanny.com
janus_rtp_domain: rtp.beta.print-nanny.com
janus_rtp_port: 5005
