---
- name: Setup OctoPrint Plugin Developer Environment
  hosts: octoprint
  vars_prompt:
    - name: octoprint_printnanny_plugin_version
      prompt: Enter a branch to checkout (git@github.com:bitsy-ai/octoprint-nanny-plugin.git)
      private: false
      default: 'main'

    - name: printnanny_profile
      prompt: Which profile should be activated? (local, sandbox, default)
      default: 'local'
      private: false
  tasks:
    - name: Set prompts as facts
      ansible.builtin.set_fact:
        printnanny_profile: '{{ printnanny_profile }}'
        octoprint_printnanny_plugin_version: '{{ octoprint_printnanny_plugin_version }}'
        octoprint_plugin_dev: true
        cacheable: true
    - name: Setup plugin developer environment
      include_role:
        name: bitsyai.printnanny.octoprint
        tasks_from: plugin_dev.yml
