---
- name: Setup OctoPrint Plugin Developer Environment
  hosts: octoprint_plugin_dev
  vars:
    octoprint_plugin_dev: true
  tasks:
    - name: Install OctoPrint (developer mode)
      include_role:
        name: bitsyai.rpi.octoprint
