---
- name: Setup OctoPrint Plugin Developer Environment
  hosts: octoprint
  tasks:
    - name: Install OctoPrint (developer mode)
      include_role:
        name: bitsyai.rpi.octoprint
      vars:
        octoprint_printnanny_plugin_dev: true
