---
# defaults file for setup role
users: []
sudoers_files:
  - content: "%wheel  ALL=(ALL)  ALL"
    file: "/etc/sudoers.d/00-wheel.conf"
  - content: "%printnanny ALL=(ALL)  ALL"
    file: "/etc/sudoers.d/00-printnanny.conf"

rpi_update_firmware: false
rpi_firmware_version: 992de83e0ea01a9765196349abb386c5c8ea8944

rpi_journald_conf:
  MaxFileSec: 14day
  ForwardToSyslog: yes
  SystemMaxUse: "10%"
  RunTimeMaxUse: "10%"

rpi_rsyslog_rotate:
  rotate: 2
  frequency: weekly
  maxage: 14 # days

ansible_facts_path: /etc/ansible/facts.d
