---
# defaults file for setup role
users: []
rpi_update_firmware: false
rpi_firmware_version: 992de83e0ea01a9765196349abb386c5c8ea8944

rpi_journald_conf:
  MaxFileSec: 14day
  ForwardToSyslog: yes
  SystemMaxUse: "10%"
  RunTimeMaxUse: "10%"

rpi_rsyslog_rotate:
  rotate: 2
  frequency: weekly
  maxage: 14 # days

ansible_facts_path: /etc/ansible/facts.d


printnanny_user: printnanny
printnanny_groups:
  - dialout
  - gpio
  - i2c
  - input
  - netdev
  - plugdev
  - spi
  - sudo
  - tty
  - video

update_user: ansible
update_groups:
  - sudo
  - printnanny

octoprint_user: pi
octoprint_groups:
  - dialout
  - gpio
  - i2c
  - input
  - plugdev
  - spi
  - sudo
  - tty
  - video

janus_user: janus
janus_groups:
  - ssl-cert
