---
# handlers file for setup
- name: restart printnanny-monitor
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-monitor
    no_block: true
    state: restarted

- name: restart printnanny-janus if running
  ansible.builtin.service_facts:
  notify:
    - check printnanny-janus running


- name: check printnanny-janus running
  ansible.builtin.debug:
    var: ansible_facts.services["printnanny-janus.service"]
  when: ansible_facts.services["printnanny-janus.service"].state == "running" and janus_config_updated.changed
  notify:
    - restart printnanny-janus

- name: restart printnanny-janus
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-janus
    no_block: true
    state: restarted


- name: restart printnanny-dash
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-dash
    no_block: true
    state: restarted
    enabled: true

- name: restart printnanny-update
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-update
    no_block: true
    state: restarted
    enabled: true

- name: restart {{ nn_rtp_service }}
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: '{{ nn_rtp_service }}'
    state: restarted
    no_block: true

- name: reload nginx
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
    no_block: true

- name: restart printnanny.target
  become: true
  ansible.builtin.systemd:
    name: printnanny.target
    state: restarted
    no_block: true
