---
# handlers file for setup
- name: restart printnanny-monitor
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-monitor
    no_block: true
    state: restarted

- name: restart printnanny-janus
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-janus
    no_block: true
    state: restarted
    enabled: true

- name: restart printnanny-mqtt
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-mqtt
    no_block: true
    state: restarted
    enabled: true

- name: restart printnanny-dash
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-dash
    no_block: true
    state: restarted
    enabled: true

- name: restart printnanny-update
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-update
    no_block: true
    state: restarted
    enabled: true

- name: restart {{ nn_rtp_service }}
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: '{{ nn_rtp_service }}'
    state: restarted
    no_block: true

- name: reload nginx
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
    no_block: true

- name: restart printnanny.target
  become: true
  ansible.builtin.systemd:
    name: printnanny.target
    state: restarted
    no_block: true
