---
# defaults file for nnstreamer

nn_capture_height: 720
nn_capture_width: 1280
nn_capture_framerate: 30

nn_tensor_height: 300
nn_tensor_width: 300

nn_framework: tensorflow-lite

nn_base_url: https://cdn.print-nanny.com/ml/print3d_20201101015829
nn_model_url: '{{ nn_base_url }}/model.tflite'
nn_label_url: '{{ nn_base_url }}/dict.txt'
nn_metadata_url: '{{ nn_metadata_url }}/metadata.json'

nn_install_dir: /opt/printnanny/nn

nn_model_file: '{{ nn_install_dir }}/model.tflite'
nn_label_file: '{{ nn_install_dir }}/dict.txt'
nn_metadata_file: '{{ nn_install_dir }}/metadata.json'

nn_user: printnanny
