- name: Install ara into ansible virtual env
  ansible.builtin.pip:
    name:
      - '{{ ara_version }}'
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ updater_venv }}'
    extra_args: '--no-cache-dir'
  when: ara_enabled
  tags:
    - metadata
# get ansible.cfg values for ara e.g.
# [defaults]
# callback_plugins=/home/leigh/.local/lib/python3.8/site-packages/ara/plugins/callback
# action_plugins=/home/leigh/.local/lib/python3.8/site-packages/ara/plugins/action
# lookup_plugins=/home/leigh/.local/lib/python3.8/site-packages/ara/plugins/lookup

- name: Get ara plugin configs
  ansible.builtin.command: '{{ updater_venv }}/bin/python -m ara.setup.ansible'
  register: ara_plugin_setup
  when: ara_enabled
  tags:
    - metadata