- name: Create /etc/ansible
  become: true
  ansible.builtin.file:
    path: /etc/ansible
    state: directory
    mode: 0755
  tags:
    - setup
    - metadata

- name: Create {{ printnanny_ansible_dir }}/collections
  become: true
  ansible.builtin.file:
    path: '{{ printnanny_ansible_dir }}/collections'
    state: directory
    mode: 0755
    owner: '{{ update_user }}'
    group: '{{ update_user }}'
  tags:
    - setup
    - metadata

- name: 'Update ansible virtualenv pip, setuptools'
  ansible.builtin.pip:
    name:
      - 'pip>21,<22'
      - setuptools
      - wheel
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ updater_venv }}'
    extra_args: '--no-cache-dir'
  tags:
    - setup
    - metadata

- name: Install ansible into virtual env
  ansible.builtin.pip:
    name:
      - '{{ ansible_updater_version }}'
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ updater_venv }}'
    extra_args: '--no-cache-dir'
  tags:
    - setup
    - requirements
    - metadata

# pin jinja2>=2.11 to support nginx_core collection's use of boolean filter
# https://github.com/nginxinc/ansible-role-nginx-config/issues/195#issuecomment-1009679890
- name: Upgrade jinja2 version
  ansible.builtin.pip:
    name:
      - '{{ jinja2_version }}'
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ updater_venv }}'
    extra_args: '--no-cache-dir'
  tags:
    - setup
    - requirements
    - metadata

# get ara configuration before rendering ansible.cfg (if enabled)
- name: Configure ara
  ansible.builtin.include_tasks: update/ara.yml
  when: ara_enabled
  tags:
    - metadata
- name: Create ansible.cfg
  become: true
  ansible.builtin.template:
    mode: 0755
    src: update/ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
    force: true
  tags:
    - metadata

- name: Create printnanny-update service
  become: true
  ansible.builtin.template:
    mode: 0644
    src: update/printnanny-update.service.j2
    dest: /etc/systemd/system/printnanny-update.service
    force: true
  tags:
    - metadata

- name: Create ansible pull hosts
  become: true
  ansible.builtin.copy:
    src: files/hosts
    dest: '{{ ansible_hosts_file }}'
    mode: 0755
  tags:
    - metadata

- name: Create {{ ansible_facts_path }}
  become: true
  ansible.builtin.file:
    path: '{{ ansible_facts_path }}'
    state: directory
    mode: 0755
  tags:
    - metadata
- name: Render /etc/ansible/facts.d/device.fact
  become: true
  ansible.builtin.copy:
    src: facts.d/device.fact
    dest: '{{ printnanny_device_fact }}'
    mode: 0755
  tags:
    - metadata
- name: Render printnanny-update.sh
  become: true
  ansible.builtin.template:
    src: printnanny-update.sh.j2
    dest: /usr/local/bin/printnanny-update
    force: true
    mode: 0775
  tags:
    - metadata
- name: Render printnanny-profile.sh
  become: true
  ansible.builtin.template:
    src: printnanny-profile.sh.j2
    dest: /usr/local/bin/printnanny-profile
    force: true
    mode: 0775
  tags:
    - metadata

- name: Render printnanny-release-channel.sh
  become: true
  ansible.builtin.template:
    src: printnanny-release-channel.sh.j2
    dest: /usr/local/bin/printnanny-release-channel
    force: true
    mode: 0775
  tags:
    - metadata

- name: Configure printnanny-update.service
  become: true
  ansible.builtin.systemd:
    name: 'printnanny-update'
    enabled: false
    no_block: true
  tags:
    - metadata
  notify:
    - restart printnanny-update
