---
# handlers file for metadata
- name: restart printnanny-monitor
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-monitor
    no_block: true
    state: restarted
    enabled: true

- name: restart printnanny-dash
  ignore_errors: true
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-dash
    no_block: true
    state: restarted
    enabled: true

- name: restart printnanny-update
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-update
    no_block: true
    state: restarted
    enabled: true

- name: restart {{ nn_rtp_service }}
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: '{{ nn_rtp_service }}'
    state: restarted
    no_block: true

- name: restart printnanny-metadata
  become: true
  ansible.builtin.systemd:
    name: printnanny-metadata
    state: restarted
    enabled: true

- name: ldconfig
  become: true
  ansible.builtin.command:
    cmd: ldconfig
