---
# handlers file for nebula
- name: restart nebula
  become: true
  ansible.builtin.systemd:
    name: nebula
    daemon_reload: true
    state: restarted

- name: systemctl daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
