---
- name: restart printnanny-janus
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-janus
    enabled: true
    no_block: true

- name: ldconfig
  become: true
  ansible.builtin.command:
    cmd: ldconfig
