---
# handlers file for ansible-role-janus-gateway

- name: restart octoprint
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: octoprint
    enabled: true
    no_block: true
