---
- name: restart janus
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: janus
    enabled: true
    no_block: true

- name: ldconfig
  become: true
  ansible.builtin.command:
    cmd: ldconfig

- name: Render janus configs
  become: true
  ansible.builtin.template:
    mode: 0775
    src: "{{ item.value }}"
    dest: "{{ janus_conf_dir }}/{{ item.value }}"
    owner: "{{ janus_user }}"
    force: true
  with_dict: "{{ janus_conf_template }}"
