---
galaxy_info:
  namespace: bitsyai.printnanny
  role_name: monitoring
  author: Leigh Johnson
  description: An Ansible role to install & configure PrintNanny on a Raspberry Pi
  company: Bitsy AI Labs


  license: GPL-3.0-only

  min_ansible_version: 2.1

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
  - name: Debian
    versions:
    - buster

  galaxy_tags:
    - system
    - raspberrypi
    - 3dprinter
    - octoprint
    - mainsail
