- name: Create janus secrets
  ansible.builtin.set_fact:
    cacheable: true
    janus_admin_secret: "{{ lookup('password', janus_admin_secret_file, length=32 ) }}"
    janus_token: "{{ lookup('password', janus_token_file, length=32 ) }}"
  tags:
    - secrets
    - metadata

- name: Render janus configs
  vars:
    janus_admin_secret: "{{ lookup('password', janus_admin_secret_file, length=32 ) }}"
    janus_token: "{{ lookup('password', janus_token_file, length=32 ) }}"
  include_role:
    name: bitsyai.printnanny.janus
    tasks_from: configs.yml
  tags:
    - secrets
    - metadata
