- name: Extract license archive
  ansible.builtin.unarchive:
    src: '{{ printnanny_license_zip }}'
    dest: '{{ printnanny_data_dir }}'
    creates: '{{ printnanny_data_dir }}/license.json'
    owner: '{{ printnanny_user }}'

- name: Set read permissions on {{ printnanny_install_dir }}
  become: true
  ansible.builtin.file:
    path: '{{ printnanny_install_dir }}'
    recurse: true
    mode: 0775
    state: directory
    owner: '{{ printnanny_user }}'

- name: Set read permissions on license.json
  become: true
  ansible.builtin.file:
    path: '{{ printnanny_data_dir }}/license.json'
    recurse: true
    mode: 0770
    state: directory
    owner: '{{ printnanny_user }}'

- name: Set read permissions on priv key
  become: true
  ansible.builtin.file:
    path: '{{ printnanny_data_dir }}/ecdsa256_pkcs8.pem'
    recurse: true
    mode: 0640
    state: directory
    owner: '{{ printnanny_user }}'

- name: Check if {{ printnanny_license_json_file }} exists
  become: true
  ansible.builtin.stat:
    path: '{{ printnanny_license_json_file }}'
  register: licence

- name: activate license
  ansible.builtin.command:
    cmd: printnanny activate
    creates: '{{ printnanny_data_dir }}/device_info.json'
  when: licence.stat.exists
