- name: Extract license archive
  ansible.builtin.unarchive:
    src: '{{ printnanny_license_zip }}'
    dest: '{{ printnanny_data_dir }}'
    creates: '{{ printnanny_data_dir }}/license.json'

- name: Check if {{ printnanny_license_json_file }} exists
  ansible.builtin.stat:
    path: '{{ printnanny_license_json_file }}'
  register: licence

- name: activate license
  ansible.builtin.command:
    cmd: printnanny activate
    creates: '{{ printnanny_data_dir }}/device_info.json'
  when: licence.stat.exists
  notify:
    - render janus configs
    - restart janus service
