---
- name: Install apt dependencies
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
        # general
        - cron
        - git
        - libssl-dev
        - nano
        - openssh-server
        - pkg-config 
        - python3-dev
        - python3-pip
        - python3-venv
        - rustc
        - sudo
        - vim
        # required by ansible.builtin.package_facts
        - python3-apt
  tags:
    - auto_upgrade
# tracking https://github.com/ansible/ansible/issues/38920
# clear apt cache if packer build run (reduce img size)
- name: Clean apt cache
  become: true
  ansible.builtin.command: apt clean
