---
- name: Add nnstreamer PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:nnstreamer/ppa
    state: present
    codename: focal

- name: Ensure ca-certificates package up-to-date
  become: true
  ansible.builtin.apt:
    update_cache: true
    state: latest
    name:
      - ca-certificates

- name: Install apt dependencies
  ansible.builtin.apt:
    update_cache: true
    name:
      # common
      - cron
      - git
      - jq
      - libssl-dev
      - nano
      - openssh-server
      - pkg-config
      - python3-dev
      - python3-pip
      - python3-venv
      - python3-apt
      - systemd
      - rustc
      - sudo
      - vim
      # required by ansible.builtin.package_facts
      - python3-apt
      # gstreamer
      - gstreamer1.0-plugins-base-apps
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-tools
      - gstreamer1.0-libav
      - libx264-dev
      - libjpeg-dev
      # openssh-server
      - openssh-server
      # nnstreamer
      - nnstreamer
      - nnstreamer-tensorflow-lite
  tags:
    - auto_update
