---
- name: Add nnstreamer PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:nnstreamer/ppa
    state: present
    codename: focal
  when: ansible_distribution_major_version == 11 and ansible_distribution == "Debian"

- name: Install apt dependencies
  become: true
  async: 300
  poll: 0
  register: apt_async
  ansible.builtin.apt:
    update_cache: true
    name:
      # common
      - cron
      - git
      - jq
      - libssl-dev
      - nano
      - openssh-server
      - pkg-config
      - python3-dev
      - python3-pip
      - python3-venv
      - rustc
      - sudo
      - vim
      # required by ansible.builtin.package_facts
      - python3-apt
      # gstreamer
      - gstreamer1.0-plugins-base-apps
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-tools
      - gstreamer1.0-libav
      - libx264-dev
      - libjpeg-dev
      # nnstreamer
      - nnstreamer
  tags:
    - auto_update
