---
# tasks file for nnstreamer
- name: Create {{ nn_install_dir }}
  become: true
  ansible.builtin.file:
    state: directory
    path: '{{ nn_install_dir }}'
    mode: 0775

- name: Download {{ nn_model_url }}
  become: true
  async: 300
  poll: 0
  register: download_nn_model
  ansible.builtin.get_url:
    url: '{{ nn_model_url }}'
    dest: '{{ nn_model_file }}'
  tags:
    - firstboot

- name: Download {{ nn_label_url }}
  become: true
  async: 300
  poll: 0
  register: download_nn_label
  ansible.builtin.get_url:
    url: '{{ nn_label_url }}'
    dest: '{{ nn_label_file }}'
  tags:
    - firstboot

- name: Download {{ nn_metadata_file }}
  become: true
  async: 300
  poll: 0
  register: download_nn_metadata
  ansible.builtin.get_url:
    url: '{{ nn_metadata_url }}'
    dest: '{{ nn_metadata_file }}'
  tags:
    - firstboot

- name: 'Render {{ nn_rtp_service }}'
  become: true
  ansible.builtin.template:
    mode: 0664
    src: 'camera/{{ nn_rtp_service }}.service.j2'
    dest: '/etc/systemd/system/{{ nn_rtp_service }}.service'
    force: true
  notify: restart {{ nn_rtp_service }}

- name: Render printnanny-monitor
  become: true
  ansible.builtin.template:
    mode: 0755
    src: camera/printnanny-monitor.sh.j2
    dest: /usr/local/bin/printnanny-monitor
    force: true

- name: Enble rpt service
  ansible.builtin.systemd:
    name: '{{ nn_rtp_service }}.service'
    enabled: true
    no_block: true

- name: Get current ldconfig
  ansible.builtin.command:
    cmd: ldconfig --print-cache
  register: ldconfig_cache

- name: Determine if libcamera installed
  ansible.builtin.set_fact:
    libcamera_installed: '{{ "libcamera" in ldconfig_cache.stdout }}'

- name: Print libcamera_installed
  ansible.builtin.debug:
    var: libcamera_installed

- name: Import libcamera tasks
  include_tasks: libcamera.yml
  when: libcamera_installed
