- name: Get installed version of printnanny
  ansible.builtin.command: printnanny --version
  ignore_errors: true
  register: installed_version
  tags:
    - auto_update

- name: Download Print Nanny Binaries
  become: true
  ansible.builtin.unarchive:
    src: '{{ printnanny_cli_url }}'
    dest: /usr/local/bin
    remote_src: true
  when: installed_version.stdout != printnanny_cli_version
  tags:
    - auto_update
  # notify:
  #   - restart mqtt
  #   - restart printnanny-license

- name: Create Print Nanny www dir
  become: true
  ansible.builtin.file:
    path: '{{ printnanny_www_templates_dir }}'
    state: directory
    mode: 0664

- name: Download Print Nanny www templates
  become: true
  ansible.builtin.unarchive:
    src: '{{ printnanny_www_templates_url }}'
    dest: '{{ printnanny_www_templates_dir }}'
    remote_src: true
  when: installed_version.stdout != printnanny_cli_version
  tags:
    - auto_update
  # notify:
  #   - restart mqtt
  #   - restart printnanny-license


- name: Create a symlink for printnanny-cli
  become: true
  ansible.builtin.file:
    src: /usr/local/bin/printnanny-cli
    dest: /usr/local/bin/printnanny
    state: link
