- name: Get installed version of printnanny
  ansible.builtin.command: printnanny --version
  ignore_errors: true
  register: installed_version
  tags:
    - auto_update

- name: Download Print Nanny CLI
  become: true
  ansible.builtin.unarchive:
    src: '{{ printnanny_cli_url }}'
    dest: /usr/local/bin
    remote_src: true
  when: installed_version.stdout != printnanny_cli_version
  tags:
    - auto_update

- name: Restart mqtt service
  become: true
  ansible.builtin.systemd:
    name: mqtt
    state: started
    enabled: true
    no_block: true
