- name: Get installed version of printnanny
  ansible.builtin.command: printnanny --version
  ignore_errors: true
  register: installed_printnanny_cli_version
  tags:
    - auto_update

- name: Check if device PKI exists
  ansible.builtin.stat:
    path: '{{ printnanny_public_key }}'
  register: device_pki

- name: Stop mqtt service before updating cli binary
  become: true
  ansible.builtin.systemd:
    name: mqtt
    state: stopped
    enabled: true
  when: installed_printnanny_cli_version != printnanny_cli_version

- name: Download Print Nanny CLI
  become: true
  ansible.builtin.unarchive:
    src: '{{ printnanny_cli_url }}'
    dest: /usr/local/bin
    remote_src: true
  when: installed_printnanny_cli_version != printnanny_cli_version
  tags:
    - auto_update

- name: Restart mqtt service
  become: true
  ansible.builtin.systemd:
    name: mqtt
    state: started
    enabled: true
  when: device_pki.stat.exists
