- name: Get installed version of printnanny
  ansible.builtin.command: printnanny --version
  ignore_errors: true
  register: installed_printnanny_cli_version
  tags:
    - auto_update

- name: Download Print Nanny CLI
  ansible.builtin.unarchive:
    src: '{{ printnanny_cli_url }}'
    dest: /usr/local/bin
    remote_src: true
    mode: 0755
    extra_opts:
      - --overwrite
  when: installed_printnanny_cli_version != printnanny_cli_version
  tags:
    - auto_update
