- name: Render /etc/ansible/facts.d/device.fact
  become: true
  ansible.builtin.copy:
    src: facts.d/device.fact
    dest: '{{ printnanny_device_fact }}'
    mode: 0755

- name: Render /etc/ansible/facts.d/license.fact
  become: true
  ansible.builtin.copy:
    src: facts.d/license.fact
    dest: '{{ printnanny_license_fact }}'
    mode: 0755
