---
# metadata available to tasks beyond this point
- name: 'Configure {{ printnanny_user }} user'
  become: true
  ansible.builtin.user:
    name: '{{ printnanny_user }}'
  tags:
    - metadata

- name: 'Configure {{ printnanny_profile_dir }}'
  become: true
  ansible.builtin.file:
    state: directory
    path: '{{ printnanny_profile_dir }}'
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_group }}'
    mode: 0755
  tags:
    - metadata

- name: 'Configure {{ printnanny_user }} groups'
  become: true
  ignore_errors: true
  ansible.builtin.user:
    name: '{{ printnanny_user }}'
    groups:
      - adm
      - dialout
      - gpio
      - i2c
      - input
      - netdev
      - plugdev
      - spi
      - sudo
      - tty
      - video
  tags:
    - metadata
- import_tasks: boot_config.yml
- import_tasks: apt.yml
- import_tasks: nginx.yml
- import_tasks: camera.yml
- import_tasks: cli.yml
- import_tasks: www.yml
- import_tasks: mqtt.yml
- name: Clean ansible_async dir
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/.ansible_async"
    state: absent

- name: Render printnanny.target
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/printnanny.target.j2
    dest: /etc/systemd/system/printnanny.target
    force: true
  tags:
    - metadata

- name: Enable printnanny.target
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: printnanny.target
    no_block: true
    daemon_reload: true
  tags:
    - metadata
