---
# tasks file for setup
- name: ansible_local.device
  ansible.builtin.debug:
    msg: '{{ ansible_local.device }}'
  when: ansible_local.device is defined
- import_tasks: users.yml
- import_tasks: boot_config.yml
- import_tasks: apt.yml
- import_tasks: log.yml
- import_tasks: cli.yml
- import_tasks: setup_license.yml
- import_tasks: factsd.yml
- import_tasks: mqtt.yml
- import_tasks: monitor.yml