---
# metadata available to tasks beyond this point
- name: 'Configure {{ printnanny_user }} user'
  become: true
  ansible.builtin.user:
    name: '{{ printnanny_user }}'
  tags:
    - metadata
- name: 'Configure {{ printnanny_user }} groups'
  become: true
  ignore_errors: true
  ansible.builtin.user:
    name: '{{ printnanny_user }}'
    groups:
      - adm
      - gpio
      - i2c
      - input
      - netdev
      - plugdev
      - spi
      - sudo
      - tty
      - video
  tags:
    - metadata
- include_tasks: boot_config.yml
- include_tasks: apt.yml
- include_tasks: camera.yml
- include_tasks: cli.yml
- include_tasks: www.yml
- include_tasks: mqtt.yml
- name: Clean ansible_async dir
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/.ansible_async"
    state: absent
