---
- include_tasks: users.yml
- name: Include Janus secrets/service
  include_role:
    name: bitsyai.rpi.janus
    tasks_from: metadata/main.yml
- include_tasks: metadata/main.yml
# metadata available to tasks beyond this point
- include_tasks: boot_config.yml
- include_tasks: apt.yml
- include_tasks: camera.yml
- include_tasks: cli.yml
- include_tasks: www.yml
- include_tasks: update/main.yml
- include_tasks: mqtt.yml
- name: Clean ansible_async dir
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/.ansible_async"
    state: absent
