---
- include_tasks: users.yml
- include_tasks: secrets.yml
# secrets available to tasks beyond this point
- include_tasks: cert.yml
# certs available to tasks beyond this point
- include_tasks: env.yml
- include_tasks: boot_config.yml
- include_tasks: apt.yml
- include_tasks: cli.yml
- include_tasks: www.yml
- include_tasks: update/main.yml
- include_tasks: mqtt.yml
- include_tasks: monitor.yml
- include_tasks: camera/main.yml
