---
- include_tasks: users.yml
- include_tasks: metadata/main.yml
- name: Include Janus secrets/service
  include_role:
    name: bitsyai.rpi.janus
    tasks_from: metadata/main.yml
# metadata available to tasks beyond this point
- name: Render config.toml
  ansible.builtin.template:
    src: config.toml.j2'
    dest: '{{ printnanny_profile_dir }}/PrintNanny.toml'
    mode: 0770
    force: true
- include_tasks: boot_config.yml
- include_tasks: apt.yml
- include_tasks: cli.yml
- include_tasks: www.yml
- include_tasks: update/main.yml
- include_tasks: mqtt.yml
- include_tasks: monitor.yml
- include_tasks: camera/main.yml
