---
# tasks file for setup
- name: ansible_local.device
  ansible.builtin.debug:
    msg: '{{ ansible_local.device }}'
  when: ansible_local.device is defined
- include_tasks: users.yml
# all tasks requiring secrets must appear after this task
- include_tasks: secrets.yml
- include_tasks: cert.yml
- include_tasks: boot_config.yml
- include_tasks: apt.yml
- include_tasks: log.yml
- include_tasks: cli.yml
- include_tasks: www.yml
- include_tasks: factsd.yml
- include_tasks: mqtt.yml
- include_tasks: monitor.yml
- include_tasks: reset_service.yml
