- name: Create printnanny-monitor.service unit
  become: true
  ansible.builtin.template:
    mode: 0664
    src: monitor.service.j2
    dest: /etc/systemd/system/printnanny-monitor.service
    force: true
  notify:
    - restart printnanny-monitor
