- name: Render printnanny-monitor
  become: true
  ansible.builtin.template:
    mode: 0755
    src: camera/printnanny-monitor.sh.j2
    dest: /usr/local/bin/printnanny-monitor
    force: true
  notify:
    - restart {{ nn_rtp_service }}
