- name: Install NGINX
  include_role:
    name: nginxinc.nginx_core.nginx
  vars:
    nginx_setup_license: false
    nginx_logrotate_conf_enable: true


- name: Configure NGINX
  include_role:
    name: nginxinc.nginx_core.nginx
  vars:
    nginx_config_debug_output: true
    nginx_config_main_template_enable: true
    config:
      main:  # Configure NGINX main core directives
        load_module: []  # String or a list of strings
          # - modules/ngx_http_js_module.so
        user:  # nginx  # Can alternatively be set to a 'username' string
          username: nginx  # Required
          group: nginx
        # worker_cpu_affinity:
        #   auto: true  # Optional boolean
        #   cpumask: 0101 1010  # Optional if 'auto' is set to 'true'
        # worker_priority: 0  # Number
        worker_processes: auto  # Number or 'auto'
        # worker_rlimit_core: 1m
        # worker_rlimit_nofile: 10000  # Number
        # worker_shutdown_timeout: 30m
        error_log:
          # /var/log/nginx/error.log
          # String, a list of strings, a dictionary, or a list of dictionaries.
          # The 'file' variable is only required when setting a 'level'.
          file: /var/log/nginx/error.log  # Required
          level: notice
          # - /var/log/nginx/error.log
          # - file: /var/log/nginx/error.log  # Required
          #   level: notice
        pid: /var/run/nginx.pid
        daemon: true  # Boolean
        # debug_points: abort  # Can be set to 'abort' or 'stop'
        # env:  # MALLOC_OPTIONS
        # String, a list of strings, a dictionary, or a list of dictionaries.
        # The 'variable' variable is only required when setting a 'value'.
        #   variable: PERL5LIB  # Required
        #   value: /data/site/modules
        #   - MALLOC_OPTIONS
        #   - variable: PERL5LIB  # Required
        #     value: /data/site/modules
        # lock_file: logs/nginx.lock
        # master_process: true  # Boolean
        # pcre_jit: false  # Boolean
        # ssl_engine: device
        # thread_pool:  # Dictionary or a list of dictionaries
        #   - name: default  # Required
        #     threads: 32  # Required boolean
        #     max_queue: 65536  # Boolean
        # timer_resolution: 1s
        # working_directory: /etc/nginx
      events:  # Configure NGINX events
        # accept_mutex: false  # Boolean
        # accept_mutex_delay: 500ms
        # debug_connection:  # String or a list of strings
        #   - localhost
        # multi_accept: false  # Boolean
        # use: epoll
        # worker_aio_requests: 32  # Number
        worker_connections: 32  # Number
      http:
        include: /etc/nginx/conf.d/*.conf  # String or a list of strings
      stream:
        include:  # String or a list of strings
          - /etc/nginx/conf.d/stream/*.conf
- name: Render /etc/nginx/conf.d/printnanny.conf
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/printnanny.conf
    mode: 0644
