- name: Render /etc/nginx/conf.d/printnanny.conf
  become: true
  ansible.builtin.template:
    src: nginx/nginx.locations.j2
    dest: /etc/nginx/conf.d/printnanny.locations
    mode: 0644

- name: Enable nginx.service
  ansible.builtin.systemd:
    name: nginx.service
    enabled: true
