- name: Install openssh-server
  ansible.builtin.apt:
    name: openssh-server

# TODO send certificate to remote for signing after user authenticates
- name: Create provisional keypair
  community.crypto.openssh_keypair:
    backend: opensshbin
    group: '{{ printnanny_user }}'
    owner: '{{ printnanny_user }}'
    path: '{{ printnanny_keys_dir }}'
    regenerate: 'full_idempotence'
    type: ecdsa
    size: 2048
  tags:
    - secrets

- name: Create '{{ printnanny_cacerts_dir }}'
  ansible.builtin.file:
    path: '{{ printnanny_cacert_dir }}'
    state: directory
    mode: 0770

- name: Download GCP LTS CA Certificate {{ gcp_lts_ca_primary }}
  ansible.builtin.get_url:
    url: '{{ gcp_lts_ca_primary }}'
    dest: '{{ printnanny_cacert_dir }}/{{ gcp_lts_ca_primary | basename }}'
    mode: 0770

- name: Download GCP LTS CA Certificate {{ gcp_lts_ca_backup }}
  ansible.builtin.get_url:
    url: '{{ gcp_lts_ca_primary }}'
    dest: '{{ printnanny_cacert_dir }}/{{ gcp_lts_ca_backup | basename }}'
    mode: 0770

- name: Create random+idempotent www secret key
  ansible.builtin.set_fact:
    printnanny_www_secret_key: "{{ lookup('password', '/dev/null length=32') }}"
  tags:
    - secret