---
# tasks file for license
- name: Check if {{ printnanny_license_json_file }} exists
  become: true
  ansible.builtin.stat:
    path: '{{ printnanny_license_json_file }}'
  register: license_json

- name: Update /etc/systemd/system/printnanny-license.service
  become: true
  ansible.builtin.template:
    mode: 0664
    src: license.service.j2
    dest: /etc/systemd/system/printnanny-license.service
    force: true
    backup: true

- name: Create '{{ printnanny_data_dir }}'
  ansible.builtin.file:
    path: '{{ printnanny_data_dir }}'
    state: directory
    mode: 0770

- name: Create '{{ printnanny_backups_dir }}'
  ansible.builtin.file:
    path: '{{ printnanny_backups_dir }}'
    state: directory
    mode: 0770

- name: Enable printnanny-license.service unit
  become: true
  ansible.builtin.systemd:
    name: printnanny-license
    enabled: true
    state: started
