---
# tasks file for license
- name: Render printnanny-license.service from template
  become: true
  ansible.builtin.template:
    mode: 0664
    src: license.service.j2
    dest: /etc/systemd/system/printnanny-license.service
    force: true
    backup: true
    validate: systemd-analyze verify printnanny-license.service
  notify:
    - systemctl daemon-reload
- name: Create '{{ printnanny_data_dir }}'
  ansible.builtin.file:
    path: '{{ printnanny_data_dir }}'
    state: directory
    mode: 0770

- name: Create '{{ printnanny_backups_dir }}'
  ansible.builtin.file:
    path: '{{ printnanny_backups_dir }}'
    state: directory
    mode: 0770

- name: Enable printnanny-license.service unit
  become: true
  ansible.builtin.systemd:
    name: printnanny-license
    enabled: true
    state: started
