- name: 'Configure {{ printnanny_user }} user/groups'
  become: true
  ansible.builtin.user:
    name: '{{ printnanny_user }}'
    groups:
      - adm
      - gpio
      - i2c
      - input
      - netdev
      - plugdev
      - spi
      - sudo
      - tty
      - users
      - video

- name: Add updater user '{{ updater_user }}' to printnanny group
  become: true
  ansible.builtin.user:
    name: '{{ updater_user }}'
    groups: '{{ printnanny_user }}'
    append: true

- name: Create {{ printnanny_install_dir }}
  become: true
  ansible.builtin.file:
    path: "{{ printnanny_install_dir }}"
    state: directory
    owner: "{{ printnanny_user }}"
    group: "{{ printnanny_group }}"
    mode: 0775

- name: Create print nanny data dir
  become: true
  ansible.builtin.file:
    path: "{{ printnanny_data_dir }}"
    state: directory
    owner: "{{ printnanny_user }}"
    group: "{{ printnanny_group }}"
    mode: 0775

- name: Create print nanny backups dir
  become: true
  ansible.builtin.file:
    path: "{{ printnanny_backups_dir }}"
    state: directory
    owner: "{{ printnanny_user }}"
    group: "{{ printnanny_group }}"
    mode: 0775
