- name: 'Configure {{ printnanny_user }} user/groups'
  ansible.builtin.user:
    name: '{{ printnanny_user }}'
    groups:
      - adm
      - gpio
      - i2c
      - input
      - netdev
      - plugdev
      - spi
      - sudo
      - tty
      - users
      - video

- name: Add updater user '{{ updater_user }}' to group sudo
  user:
    name: '{{ updater_user }}'
    groups: '{{ printnanny_user }}'
    append: true
