- name: Create Print Nanny www dir
  become: true
  ansible.builtin.file:
    path: '{{ printnanny_www_dir }}'
    state: directory
    mode: 0664

- name: Create Print Nanny www templates dir
  become: true
  ansible.builtin.file:
    path: '{{ printnanny_www_templates_dir }}'
    state: directory
    mode: 0664

- name: Download Print Nanny www templates
  become: true
  ansible.builtin.unarchive:
    src: '{{ printnanny_www_templates_url }}'
    dest: '{{ printnanny_www_templates_dir }}'
    remote_src: true
  when: installed_version.stdout != printnanny_cli_version
  tags:
    - auto_update

- name: Create random+idempotent www secret key
  ansible.builtin.set_fact:
    printnanny_www_secret_key: "{{ lookup('password', '/dev/null length=32') }}"
  tags:
    - secret

- name: Render Print Nanny Dashboard env from template
  become: true
  ansible.builtin.template:
    mode: 0664
    src: rocket.toml.j2
    dest: '{{ printnanny_www_dir }}/rocket.toml'
    force: true

- name: Enable Print Nanny Dashboard service
  become: true
  ansible.builtin.systemd:
    service: printnanny-dash
    enabled: true
    state: started
    no_block: true
