- name: Create Print Nanny www dir
  become: true
  ansible.builtin.file:
    path: '{{ printnanny_www_dir }}'
    state: directory
    mode: 0664
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_user }}'

- name: Create Print Nanny www templates dir
  become: true
  ansible.builtin.file:
    path: '{{ printnanny_www_templates_dir }}'
    state: directory
    mode: 0664
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_user }}'

- name: Download Print Nanny www templates
  become: true
  ansible.builtin.unarchive:
    src: '{{ printnanny_www_templates_url }}'
    dest: '{{ printnanny_www_templates_dir }}'
    remote_src: true
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_user }}'
  when: installed_version.stdout != printnanny_cli_version
  tags:
    - auto_update

- name: Render Print Nanny Dashboard env from template
  become: true
  ansible.builtin.template:
    mode: 0664
    src: rocket.toml.j2
    dest: '{{ printnanny_www_dir }}/rocket.toml'
    force: true
  when: printnanny_www_secret_key is defined

- name: Enable Print Nanny Dashboard service
  become: true
  ansible.builtin.systemd:
    service: printnanny-dash
    enabled: true
    state: started
    no_block: true
