- name: Create Print Nanny www dir
  become: true
  ansible.builtin.file:
    path: '{{ printnanny_www_dir }}'
    state: directory
    mode: 0775
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_user }}'

- name: Create Print Nanny www templates dir
  become: true
  ansible.builtin.file:
    path: '{{ printnanny_www_templates_dir }}'
    state: directory
    mode: 0775
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_user }}'

- name: Download Print Nanny www templates
  become: true
  ansible.builtin.unarchive:
    src: '{{ printnanny_www_templates_url }}'
    dest: '{{ printnanny_www_templates_dir }}'
    remote_src: true
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_user }}'
  when: installed_version.stdout != printnanny_cli_version
  notify:
    - restart printnanny-dash

- name: Render Print Nanny Dashboard Rocket.toml
  become: true
  ansible.builtin.template:
    mode: 0660
    src: www/Rocket.toml.j2
    dest: '{{ printnanny_www_dir }}/Rocket.toml'
    force: true
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_user }}'
  when: printnanny_www_secret_key is defined
  tags:
    - secret
    - env
    - metadata
  notify:
    - restart printnanny-dash

- name: Render Print Nanny Dashboard service from template
  become: true
  ansible.builtin.template:
    mode: 0664
    src: systemd/dash.service.j2
    dest: /etc/systemd/system/printnanny-dash.service
    force: true

- name: Enable Print Nanny Dashboard service
  become: true
  ansible.builtin.systemd:
    service: printnanny-dash
    enabled: true
    state: started
    no_block: true
