# TODO send certificate to remote for signing after user authenticates
- name: Create '{{ printnanny_keys_dir }}'
  become: true
  ansible.builtin.file:
    path: '{{ printnanny_keys_dir }}'
    state: directory
    mode: 0750
    group: '{{ printnanny_user }}'
    owner: '{{ printnanny_user }}'
  tags:
    - firstboot

- name: Create provisional private key
  become: true
  community.crypto.openssl_privatekey:
    group: '{{ printnanny_user }}'
    owner: '{{ printnanny_user }}'
    path: '{{ printnanny_ec_private_key }}'
    regenerate: 'full_idempotence'
    type: ECC
    # prime256v1
    curve: secp256r1
    format: pkcs8
  tags:
    - secret
    - firstboot

- name: Extract provisional public key
  become: true
  community.crypto.openssl_publickey:
    group: '{{ printnanny_user }}'
    owner: '{{ printnanny_user }}'
    privatekey_path: '{{ printnanny_ec_private_key }}'
    path: '{{ printnanny_ec_public_key }}'
  tags:
    - secret
    - firstboot
  register: printnanny_ec_public_key_output

- name: Write md5 fingerprint to file
  become: true
  ansible.builtin.copy:
    content: '{{ printnanny_ec_public_key_output.fingerprint.md5 }}'
    dest: '{{ printnanny_ec_fingerprint_md5 }}'
    mode: 0644
    group: '{{ printnanny_user }}'
    owner: '{{ printnanny_user }}'
  tags:
    - secret
    - firstboot

- name: Set printnanny_ec_fingerprint
  ansible.builtin.set_fact:
    printnanny_ec_fingerprint_md5_content: "{{ printnanny_ec_public_key_output.fingerprint.md5 }}"
    cacheable: true
  tags:
    - secret
    - firstboot

- name: Create '{{ printnanny_cacerts_dir }}'
  become: true
  ansible.builtin.file:
    path: '{{ printnanny_cacerts }}'
    state: directory
    mode: 0775
    group: '{{ printnanny_user }}'
    owner: '{{ printnanny_user }}'
  tags:
    - firstboot

- name: Download GCP LTS CA Certificate {{ gcp_lts_ca_primary }}
  become: true
  ansible.builtin.get_url:
    url: '{{ gcp_lts_ca_primary }}'
    dest: '{{ printnanny_cacerts }}/{{ gcp_lts_ca_primary | basename }}'
    mode: 0771
    group: '{{ printnanny_user }}'
    owner: '{{ printnanny_user }}'
  tags:
    - firstboot

- name: Download GCP LTS CA Certificate {{ gcp_lts_ca_backup }}
  become: true
  ansible.builtin.get_url:
    url: '{{ gcp_lts_ca_backup }}'
    dest: '{{ printnanny_cacerts }}/{{ gcp_lts_ca_backup | basename }}'
    mode: 0771
    group: '{{ printnanny_user }}'
    owner: '{{ printnanny_user }}'
  tags:
    - firstboot

- name: Include OctoPrint vars
  ansible.builtin.include_role:
    name: bitsyai.printnanny.octoprint
    tasks_from: facts.yml
    public: true
    apply:
      tags:
        - firstboot
  when: octoprint_python_version is not defined
  tags:
    - firstboot

- name: Render config.toml
  vars:
    janus_edge_admin_secret: "{{ lookup('password', janus_edge_admin_secret_file, length=32 ) }}"
    janus_edge_token: "{{ lookup('password', janus_edge_token_file, length=32 ) }}"
    janus_edge_streaming_secret: "{{ lookup('password', janus_edge_streaming_secret_file, length=32 ) }}"
    janus_edge_streaming_pin: "{{ lookup('password', janus_edge_streaming_pin_file, length=32 ) }}"
  ansible.builtin.template:
    src: config.toml.j2
    dest: '{{ printnanny_firstboot_toml }}'
    mode: 0644
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_user }}'
  tags:
    - secret
    - firstboot
