- name: Create '{{ printnanny_profile_dir }}'
  ansible.builtin.file:
    state: directory
    path: '{{ printnanny_profile_dir }}'
    mode: 0755
    owner: '{{ printnanny_user }}'
  tags:
    - firstboot

- name: Create {{ printnanny_data_dir }}
  become: true
  ansible.builtin.file:
    path: "{{ printnanny_data_dir }}"
    state: directory
    owner: "{{ printnanny_user }}"
    group: "{{ printnanny_group }}"
    mode: 0775
    recurse: true
  tags:
    - firstboot

- name: Create {{ printnanny_keys_dir }}
  become: true
  ansible.builtin.file:
    path: "{{ printnanny_keys_dir }}"
    state: directory
    owner: "{{ printnanny_user }}"
    group: "{{ printnanny_group }}"
    mode: 0771
  tags:
    - firstboot

- name: Create {{ printnanny_backups_dir }}
  become: true
  ansible.builtin.file:
    path: "{{ printnanny_backups_dir }}"
    state: directory
    owner: "{{ printnanny_user }}"
    group: "{{ printnanny_group }}"
    mode: 0775
  tags:
    - firstboot

- name: env firstbook tasks
  include_tasks: env.yml

- name: www firstbook tasks
  include_tasks: www.yml
- name: janus firstbook tasks
  include_tasks: janus.yml
  when: janus_local_enabled
- name: mqtt firstbook tasks
  include_tasks: mqtt.yml

- name: Render config.toml
  vars:
    janus_local_admin_secret: "{{ lookup('password', janus_local_admin_secret_file, length=32 ) }}"
    janus_local_token: "{{ lookup('password', janus_local_token_file, length=32 ) }}"
    janus_local_streaming_secret: "{{ lookup('password', janus_local_streaming_secret_file, length=32 ) }}"
    janus_local_streaming_pin: "{{ lookup('password', janus_local_streaming_pin_file, length=32 ) }}"
  ansible.builtin.template:
    src: config.toml.j2
    dest: '{{ printnanny_config_toml }}'
    mode: 0644
    force: true
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_user }}'
  notify:
    - restart printnanny-dash
  tags:
    - secret
    - firstboot

- name: Render printnanny-firstboot.service template
  become: true
  ansible.builtin.template:
    src: printnanny-firstboot.service.j2
    dest: /etc/systemd/system/printnanny-firstboot.service
    mode: 0664
    force: true
  tags:
    - firstboot

- name: Enable firstboot service
  become: true
  ansible.builtin.systemd:
    name: printnanny-firstboot.service
    enabled: true
    no_block: true
  tags:
    - firstboot
