- name: Create '{{ printnanny_profile_dir }}'
  ansible.builtin.file:
    state: directory
    path: '{{ printnanny_profile_dir }}'
    mode: 0755
    owner: '{{ printnanny_user }}'
  tags:
    - firstboot

- name: Create {{ printnanny_data_dir }}
  become: true
  ansible.builtin.file:
    path: "{{ printnanny_data_dir }}"
    state: directory
    owner: "{{ printnanny_user }}"
    group: "{{ printnanny_group }}"
    mode: 0775
    recurse: true
  tags:
    - firstboot

- name: Create {{ printnanny_keys_dir }}
  become: true
  ansible.builtin.file:
    path: "{{ printnanny_keys_dir }}"
    state: directory
    owner: "{{ printnanny_user }}"
    group: "{{ printnanny_group }}"
    mode: 0771
  tags:
    - firstboot

- name: Create {{ printnanny_backups_dir }}
  become: true
  ansible.builtin.file:
    path: "{{ printnanny_backups_dir }}"
    state: directory
    owner: "{{ printnanny_user }}"
    group: "{{ printnanny_group }}"
    mode: 0775
  tags:
    - firstboot

- name: env firstbook tasks
  include_tasks: firstboot/env.yml

- name: www firstbook tasks
  include_tasks: firstboot/www.yml
- name: janus firstbook tasks
  include_tasks: firstboot/janus.yml
  when: janus_local_enabled

- name: certs
  include_tasks: firstboot/certs.yml
