- name: Create {{ janus_conf_dir }}
  become: true
  ansible.builtin.file:
    state: directory
    mode: 0775
    path: '{{ janus_conf_dir }}'
  tags:
    - metadata

- name: Render janus configs
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '{{ janus_conf_dir }}/{{ item }}'
    owner: '{{ janus_user }}'
    group: '{{ janus_group }}'
    mode: 0644
    force: true
  with_items: '{{ janus_conf_template }}'
  tags:
    - metadata
    - secret
  register: janus_config_updated

- name: Populate Ansible service_facts
  ansible.builtin.service_facts:


- name: Notify restart printnanny-janus if running
  ansible.builtin.debug:
    var: ansible_facts.services["printnanny-janus.service"]
  when: ansible_facts.services["printnanny-janus.service"].state == "running" and janus_config_updated.changed
  notify:
    - restart printnanny-janus
