---
# Build libnice
- name: 'Create {{ janus_build_dir.path }}/venv'
  ansible.builtin.pip:
    name: 
        - 'pip>21,<22'
        - setuptools
        - wheel
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ janus_build_dir.path }}/venv'
    extra_args: '--no-cache-dir'

- name: Install meson and ninja build systems
  ansible.builtin.pip:
    name:
      - meson 
    virtualenv: "{{ janus_build_dir.path }}/venv"
    virtualenv_command: /usr/bin/python3 -m venv
    extra_args: '--no-cache-dir'

- name: Clone libnice
  git:
    repo: "{{ janus_libnice_repo }}"
    dest: "{{ janus_libnice_build_dir.path }}"
    version: "{{ janus_libnice_version }}"

- name: Run libnice meson build
  command:
    cmd: "meson --prefix={{ janus_lib_prefix }} build"
    chdir: "{{ janus_libnice_build_dir.path }}"
  when: janus_upgrade_available
  environment:
    PATH: "{{ janus_build_dir.path }}/venv/bin:{{ ansible_env.PATH }}"

- name: Configure libnice ninja build
  command:
    cmd: "ninja -C build"
    chdir: "{{ janus_libnice_build_dir.path }}"
  when: janus_upgrade_available
  environment:
    PATH: "{{ janus_build_dir.path }}/venv/bin:{{ ansible_env.PATH }}"

- name: Install libnice
  become: true
  command:
    cmd: "ninja -C build install"
    chdir: "{{ janus_libnice_build_dir.path }}"
  when: janus_upgrade_available
  environment:
    PATH: "{{ janus_build_dir.path }}/venv/bin:{{ ansible_env.PATH }}"
