---
- name: Clone libwebsockets
  ansible.builtin.git:
    repo: "{{ janus_libwebsockets_repo }}"
    dest: "{{ janus_libwebsockets_build_dir.path }}"
    version: "{{ janus_libwebsockets_version }}"
  when: janus_upgrade_available
  tags:
    - janus
    - setup
    - auto_update

- name: Make websockets build configs
  ansible.builtin.command:
    cmd: cmake -DLWS_MAX_SMP=1 -DLWS_WITHOUT_EXTENSIONS=0 -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" .
    chdir: "{{ janus_libwebsockets_build_dir.path }}"
  when: janus_upgrade_available
  tags:
    - janus
    - setup
    - auto_update

- name: Make websockets library
  ansible.builtin.command:
    cmd: make
    chdir: "{{ janus_libwebsockets_build_dir.path }}"
  when: janus_upgrade_available
  tags:
    - janus
    - setup
    - auto_update

- name: Install websockets library
  become: true
  ansible.builtin.command:
    cmd: make install
    chdir: "{{ janus_libwebsockets_build_dir.path }}"
  when: janus_upgrade_available
  tags:
    - janus
    - setup
    - auto_update
