---
# Build notes
# Libs conforming to Debian Multiarch are installed to /usr/local/lib/$(gcc -dumpmachine)/
# https://wiki.debian.org/Multiarch
- name: ansible_local.janus
  ansible.builtin.debug:
    msg: '{{ ansible_local.janus }}'
  when: ansible_local.janus is defined

- name: debug janus_upgrade_available={{ janus_upgrade_available }}
  ansible.builtin.debug:
    msg: 'janus_version={{ janus_version }} ansible_local.janus.version={{ ansible_local.janus.version }}'

- import_tasks: factsd.yml

- name: Create temporary janus build directory
  ansible.builtin.tempfile:
    state: directory
    prefix: janus
  register: janus_build_dir

- name: Create temporary websockets build directory
  ansible.builtin.tempfile:
    state: directory
    prefix: libwebsockets
  register: janus_libwebsockets_build_dir

- name: Create temporary libnice build directory
  ansible.builtin.tempfile:
    state: directory
    prefix: libnice
  register: janus_libnice_build_dir

- name: Create temporary usrsctp build directory
  ansible.builtin.tempfile:
    state: directory
    prefix: usrsctp
  register: janus_usrsctp_build_dir

- name: Create temporary libsrtp build directory
  ansible.builtin.tempfile:
    state: directory
    prefix: libsrtp
  register: janus_libsrtp_build_dir

- name: Create janus user
  become: true
  ansible.builtin.user:
    name: '{{ janus_user }}'
    shell: /bin/bash
    groups: '{{ janus_groups }}'
    append: true

- name: Build janus-gateway from source
  import_tasks: build.yml
  when: janus_upgrade_available

- name: Janus systemd unit
  import_tasks: systemd.yml

- name: "Delete {{ janus_build_dir.path }} build directory"
  ansible.builtin.file:
    path: "{{ janus_build_dir.path }}"
    state: absent

- name: "Delete {{ janus_libwebsockets_build_dir.path }} build directory"
  ansible.builtin.file:
    path: "{{ janus_libwebsockets_build_dir.path }}"
    state: absent

- name: "Delete {{ janus_libnice_build_dir.path }} build directory"
  ansible.builtin.file:
    path: "{{ janus_libnice_build_dir.path }}"
    state: absent

- name: "Delete {{ janus_libsrtp_build_dir.path }} build directory"
  ansible.builtin.file:
    path: "{{ janus_libsrtp_build_dir.path }}"
    state: absent

- name: "Delete {{ janus_usrsctp_build_dir.path }} build directory"
  ansible.builtin.file:
    path: "{{ janus_usrsctp_build_dir.path }}"
    state: absent
