---
- name: Create janus user
  become: true
  ansible.builtin.user:
    name: '{{ janus_user }}'
    shell: /bin/bash
    groups: '{{ janus_groups }}'
    append: true
  tags:
    - metadata
- name: Stat janus binary
  ansible.builtin.stat:
    path: /opt/janus/bin/janus
  register: janus_bin

- name: ansible_local
  ansible.builtin.debug:
    var: ansible_local

# all tasks requiring access to secrets must appear after this task
- include_tasks: build/main.yml
  when: janus_version != janus_installed_version

- include_tasks: factsd.yml
- name: Update /etc/systemd/system/janus.service
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/janus.service.j2
    dest: /etc/systemd/system/janus.service
    force: true
  notify:
    - restart janus
