---
- name: Debug ansible_local
  ansible.builtin.debug:
    var: ansible_local

- name: Debug janus_version
  ansible.builtin.debug:
    var: janus_version

- name: Debug ansible_local.janus.version
  ansible.builtin.debug:
    var: ansible_local.janus.version

# all tasks requiring access to secrets must appear after this task
- include_tasks: build/main.yml
  when: ansible_local.janus.version is not defined or (janus_version != ansible_local['janus']['version'])

- include_tasks: configs.yml
- include_tasks: factsd.yml

- name: Update /etc/systemd/system/printnanny-janus.service
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/janus.service.j2
    dest: /etc/systemd/system/printnanny-janus.service
    force: true
  notify:
    - restart printnanny-janus
