---
- name: Stat janus binary
  ansible.builtin.stat:
    path: /opt/janus/bin/janus
  register: janus_bin

- name: Debug ansible_local
  ansible.builtin.debug:
    var: ansible_local

- name: Debug janus_version
  ansible.builtin.debug:
    var: janus_version

- name: Debug janus_intalled_version
  ansible.builtin.debug:
    var: janus_installed_version

# all tasks requiring access to secrets must appear after this task
- include_tasks: build/main.yml
  when: janus_version != janus_installed_version

- include_tasks: configs.yml
- include_tasks: factsd.yml

- name: Update /etc/systemd/system/printnanny-janus.service
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/janus.service.j2
    dest: /etc/systemd/system/printnanny-janus.service
    force: true
  register: janus_config_updated
- name: Populate Ansible service_facts
  ansible.builtin.service_facts:


- name: Notify restart printnanny-janus if running
  ansible.builtin.debug:
    var: ansible_facts.services["printnanny-janus.service"]
  when: ansible_facts.services["printnanny-janus.service"].state == "running" and janus_config_updated.changed
  notify:
    - restart printnanny-janus
