---
# Build notes
# Libs conforming to Debian Multiarch are installed to /usr/local/lib/$(gcc -dumpmachine)/
# https://wiki.debian.org/Multiarch
- name: ansible_local.janus
  ansible.builtin.debug:
    msg: '{{ ansible_local.janus }}'
  when: ansible_local.janus is defined

- name: debug janus_upgrade_available={{ janus_upgrade_available }}
  ansible.builtin.debug:
    msg: 'janus_version={{ janus_version }} ansible_local.janus={{ ansible_local.janus }}'
  when: ansible_local.janus is defined

- name: Create janus user
  become: true
  ansible.builtin.user:
    name: '{{ janus_user }}'
    shell: /bin/bash
    groups: '{{ janus_groups }}'
    append: true

- name: Build janus from source
  import_tasks: build.yml
  when: janus_build_source == True

# - name: Install Janus from deb
#   import_tasks: deb.yml
#   when: ansible_os_family == "Debian" and janus_build_source == False

- import_tasks: factsd.yml


- name: Configure janus.service
  import_tasks: systemd.yml
