---
- name: Set janus_upgrade_available
  ansible.builtin.set_fact:
    janus_upgrade_available: "{{ ansible_local['janus']['version'] != janus_version }}"
  when: ansible_local.janus is defined

- name: print janus_version
  ansible.builtin.debug:
    var: janus_version

- name: print janus_upgrade_available
  ansible.builtin.debug:
    var: janus_upgrade_available

- name: ansible_local
  ansible.builtin.debug:
    var: ansible_local

# all tasks requiring access to secrets must appear after this task
- include_tasks: metadata/main.yml
- include_tasks: build/main.yml
  when: janus_build_source == True and janus_upgrade_available

- include_tasks: factsd.yml
- name: Update /etc/systemd/system/janus.service
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/janus.service.j2
    dest: /etc/systemd/system/janus.service
    force: true
  notify:
    - restart janus
