- name: Create {{ janus_conf_dir }}
  become: true
  ansible.builtin.file:
    state: directory
    mode: 0775
    path: '{{ janus_conf_dir }}'

- name: Create janus secrets
  ansible.builtin.set_fact:
    janus_admin_secret: "{{ lookup('password', janus_admin_secret_file, length=32 ) }}"
    janus_token: "{{ lookup('password', janus_token_file, length=32 ) }}"
  tags:
    - secrets

- name: Render janus-gateway config templates
  become: true
  ansible.builtin.template:
    mode: 0775
    src: "{{ item.value }}"
    dest: "{{ janus_conf_dir }}/{{ item.value }}"
    owner: "{{ janus_user }}"
    force: true
    backup: true
  with_dict: "{{ janus_conf_template }}"
  when: janus_admin_secret is defined
  notify:
    - restart janus

- name: Render {{ janus_env_file }}
  become: true
  ansible.builtin.template:
    mode: 0771
    src: "systemd/janus.env.j2"
    dest: "{{ janus_env_file }}"
    owner: "{{ janus_user }}"
    force: true
    backup: true
  when: janus_admin_secret is defined
  notify:
    - restart janus

- name: Update /etc/systemd/system/janus.service
  become: true
  ansible.builtin.template:
    mode: 0775
    src: systemd/janus.service.j2
    dest: /etc/systemd/system/janus.service
    force: true
  notify:
    - restart janus
