- name: Render janus-gateway config templates
  become: true
  ansible.builtin.template:
    mode: 0660
    src: "{{ item.value }}"
    dest: "{{ janus_conf_dir }}/{{ item.value }}"
  with_dict: "{{ janus_conf_template }}"
  when: janus_auth.api_secret is defined

- name: Render janus-gateway systemd unit
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/janus.service.j2
    dest: /etc/systemd/system/janus.service
  notify:
    - restart janus service

- name: Enable service janus
  become: true
  ansible.builtin.systemd:
    name: janus
    enabled: '{{ printnanny_device is defined }}'
