- name: Render janus-gateway config templates
  become: true
  ansible.builtin.template:
    mode: 0660
    src: "{{ item.value }}"
    dest: "{{ janus_conf_dir }}/{{ item.value }}"
    owner: "{{ janus_user }}"
    force: true
    backup: true
  with_dict: "{{ janus_conf_template }}"
  when: ansible_local.license.janus_admin_secret is defined

- name: Render janus-gateway systemd unit
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/janus.service.j2
    dest: /etc/systemd/system/janus.service
    force: true
    backup: true
    validate: systemd-analyze verify %s
  notify:
    - reload janus service
  when: ansible_local.license.janus_admin_secret is defined
