- name: Create {{ janus_conf_dir }}
  become: true
  ansible.builtin.file:
    state: directory
    mode: 0660

- name: Render janus-gateway config templates
  become: true
  ansible.builtin.template:
    mode: 0660
    src: "{{ item.value }}"
    dest: "{{ janus_conf_dir }}/{{ item.value }}"
    owner: "{{ janus_user }}"
    force: true
    backup: true
  with_dict: "{{ janus_conf_template }}"
  when: janus_admin_secret != None
  notify:
    - restart janus

- name: Render {{ janus_env_file }}
  become: true
  ansible.builtin.template:
    mode: 0660
    src: "systemd/janus.env.j2"
    dest: "{{ janus_env_file }}"
    owner: "{{ janus_user }}"
    force: true
    backup: true
  when: janus_admin_secret != None
  notify:
    - restart janus

- name: Update /etc/systemd/system/janus.service
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/janus.service.j2
    dest: /etc/systemd/system/janus.service
    force: true
  notify:
    - restart janus
