---
# defaults file for ansible_pull

bitsyai_path: /opt/bitsy-ai
ansible_pull_user: ansible
ansible_pull_version: 'ansible>4,<5'
ansible_pull_venv: "/home/{{ ansible_pull_user }}/ansible/venv"

ansible_pull_items:
  - name: 'bitsy-update-rpi'
    src: 'bitsyai.rpi.playbooks.automatic_updates'
    url: 'https://github.com/bitsy-ai/ansible-collection-rpi'
    checkout: 'main'
    playbook: automatic_updates.yml
    timer:
      OnUnitInactiveSec: 3600 # update every hour
      RandomizedDelaySec: 60 # offset by 60 seconds of jitter
      OnStartupSec: 120 # always update 2 minutes after booting
