---
# handlers file for setup
- name: restart printnanny-monitor
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-monitor
    no_block: true
    state: restarted
    enable: true

- name: restart janus
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: janus
    no_block: true
    state: restarted
    enable: true

- name: restart mqtt
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: mqtt
    no_block: true
    state: restarted
    enable: true
  when: license_json.stat.exists

- name: restart printnanny-license
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-license
    no_block: true
    state: restarted
    enable: true
  when: license_json.stat.exists
