---
# handlers file for setup
- name: restart printnanny-monitor
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-monitor
    state: restarted

- name: render janus configs
  become: true
  ansible.builtin.template:
    mode: 0660
    src: "{{ item.value }}"
    dest: "{{ janus_conf_dir }}/{{ item.value }}"
    force: true
    backup: true
  with_dict: "{{ janus_conf_template }}"
  when: ansible_local.license.janus_admin_secret is defined

- name: restart janus service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: janus
    state: restarted

- name: restart mqtt service
  become: true
  ansible.builtin.systemd:
    name: mqtt
    state: restarted
  when: license_json.stat.exists

- name: restart printnanny-license service
  become: true
  ansible.builtin.systemd:
    name: printnanny-license
    state: restarted
  when: license_json.stat.exists
