---
# defaults file for setup
# defaults file for ansible-role-print-nanny
tflite_version: v2.5.1

printnanny_install_dir: /opt/printnanny
printnanny_data_dir: '{{ printnanny_install_dir }}/data'
printnanny_backups_dir: "{{ printnanny_install_dir }}/backups"
printnanny_license_zip: /boot/printnanny_license.zip
printnanny_license_json_file: '{{ printnanny_data_dir }}/license.json'

ansible_facts_path: /etc/ansible/facts.d
printnanny_device_fact: /etc/ansible/facts.d/device.fact
printnanny_license_fact: /etc/ansible/facts.d/license.fact
printnanny_janus_fact: /etc/ansible/facts.d/janus.fact

printnanny_cli_version: 0.5.0
printnanny_cli_url: 'https://github.com/bitsy-ai/printnanny-cli/releases/download/v{{ printnanny_cli_version }}/printnanny-{{ ansible_architecture }}-unknown-linux-gnu.tar.gz'
printnanny_ansible_version: 'ansible>4,<5'
printnanny_update_schedule: '*/15 * * * *'
printnanny_user: printnanny
printnanny_group: printnanny
