---
# defaults file for setup
# defaults file for ansible-role-print-nanny
tflite_version: v2.5.1

##
# printnanny_ vars
##
printnanny_profile: default

printnanny_api_url: https://print-nanny.com
printnanny_service_dir: /etc/systemd/printnanny.d
printnanny_runtime_dir: /var/run/printnanny
printnanny_env: '{{ printnanny_runtime_dir }}/{{ printnanny_profile }}.env'
printnanny_env_sh: '{{ printnanny_runtime_dir }}/{{printnanny_profile}}.sh'

printnanny_install_dir: '/opt/printnanny'
printnanny_profile_dir: '{{ printnanny_install_dir }}/{{ printnanny_profile }}'
printnanny_cacerts: '{{ printnanny_profile_dir }}/ca-certificates'
printnanny_data_dir: '{{ printnanny_profile_dir }}/data'
printnanny_keys_dir: '{{ printnanny_profile_dir }}/keys'
printnanny_ecdsa_private_key: '{{ printnanny_keys_dir }}/id_ecdsa'
printnanny_ecdsa_public_key: '{{ printnanny_ecdsa_private_key }}.pub'

printnanny_config_toml: '{{ printnanny_profile_dir }}/PrintNanny.toml'
printnanny_backups_dir: "{{ printnanny_profile_dir }}/backups"
printnanny_ansible_dir: "{{ printnanny_install_dir }}/ansible"

printnanny_www_dir: '{{ printnanny_profile_dir }}/www'
printnanny_www_secret_file: '{{ printnanny_www_dir }}/key'
printnanny_www_templates_dir: '{{ printnanny_www_dir }}/templates'
printnanny_www_address: "0.0.0.0"
printnanny_www_port: 9001
printnanny_www_log_level: "normal"

ansible_facts_path: /etc/ansible/facts.d
printnanny_device_fact: /etc/ansible/facts.d/device.fact
printnanny_license_fact: /etc/ansible/facts.d/license.fact
printnanny_janus_fact: /etc/ansible/facts.d/janus.fact

printnanny_cli_version: 0.12.4
printnanny_cli_repo: 'https://github.com/bitsy-ai/printnanny-cli'
printnanny_cli_url: '{{ printnanny_cli_repo }}/releases/download/v{{ printnanny_cli_version }}/printnanny-{{ ansible_architecture }}-unknown-linux-gnu.tar.gz'
printnanny_www_templates_url: '{{ printnanny_cli_repo }}/releases/download/v{{ printnanny_cli_version }}/printnanny-www-templates.tar.gz'
printnanny_ansible_version: 'ansible>4,<5'
printnanny_update_schedule: '*/15 * * * *'
printnanny_user: printnanny
printnanny_group: printnanny

printnanny_ssl_key_size: 2048
printnanny_ssl_key_type: DSA
printnanny_ssl_dir: '{{ janus_install_dir }}/ssl'
printnanny_ssl_crt_dir: '{{ janus_install_dir }}/ssl/crt'
printnanny_ssl_key_dir: '{{ janus_install_dir }}/ssl/private'
printnanny_ssl_csr_dir: '{{ janus_install_dir }}/ssl/csr'
printnanny_ssl_cert: '{{ printnanny_ssl_crt_dir}}/janus.crt'
printnanny_ssl_key: '{{ printnanny_ssl_key_dir}}/janus.pem'
printnanny_ssl_csr: '{{ printnanny_ssl_csr_dir }}/janus.csr'

printnanny_ssl_country_name: 'US'
printnanny_ssl_email_address: support@print-nanny.com
printnanny_ssl_organization_name: 'Bitsy AI Labs, LLC'

##
# gcp_ vars
##
gcp_lts_ca_primary: https://pki.goog/gtsltsr/gtsltsr.crt
gcp_lts_ca_backup: https://pki.goog/gsr4/GSR4.crt

##
# updater_ vars
##

updater_app_name: printnanny
updater_playbooks:
    - bitsyai.rpi.printnanny.update.system

updater_release_channel: '{{ printnanny.release_channel | default("main") }}'
updater_collection_url: 'git+https://github.com/bitsy-ai/ansible-collection-rpi.git,{{ updater_release_channel }}'

updater_user: ansible
updater_venv: '{{ printnanny_ansible_dir }}/venv'

ansible_updater_version: 'ansible-core>2.11,<2.12'
ansible_collection_updater: ansible-updater
updater_tmpfs: '/var/run/{{ updater_app_name }}'
ansible_lockfile: '/var/run/{{ updater_app_name }}/ansible.lock'

ansible_hosts_file: /etc/ansible/hosts
ansible_config:
    fact_caching_timeout: 86400
    fact_caching: jsonfile
    fact_caching_connection: /etc/ansible/facts.json

##
# ara_ vars
##
# ara configuration (optional)
# https://ara.readthedocs.io/

ara_enabled: true
ara_version: 'ara>1.5,<1.6'

# ara configuration values: https://ara.readthedocs.io/en/latest/ansible-plugins-and-use-cases.html
ara_api_client: http
ara_api_server: https://ara.print-nanny.com
ara_api_timeout: 15
ara_callback_threads: 4
ara_ignored_arguments: vault_password_files
ara_default_labels: 'channel:{{updater_release_channel}}'
ara_argument_labels: check,subset,tags

##
# gstreamer vars
##

gstreamer_num_buffers: 3
gstreamer_config_interval: 1
gstreamer_video_src: 'v4l2src'

gstreamer_video_w: 1280
gstreamer_video_h: 720
gstreamer_rtp_host: "127.0.0.1"
gstreamer_rtp_port: 5004

##
# nnstreamer vars
##

nn_rtp_service: nn-rtp
nn_x_service: nn-x
nn_capture_height: 720
nn_capture_width: 1280
nn_capture_framerate: 30

nn_tensor_height: 300
nn_tensor_width: 300

nn_framework: tensorflow-lite

nn_base_url: https://cdn.print-nanny.com/ml/print3d_20201101015829
nn_model_url: '{{ nn_base_url }}/model.tflite'
nn_label_url: '{{ nn_base_url }}/dict.txt'
nn_metadata_url: '{{ nn_metadata_url }}/metadata.json'

nn_install_dir: '{{printnanny_profile_dir}}/nn'

nn_model_file: '{{ nn_install_dir }}/model.tflite'
nn_label_file: '{{ nn_install_dir }}/dict.txt'
nn_metadata_file: '{{ nn_install_dir }}/metadata.json'

##
# honeycomb vars
##
honeycomb_dataset: 'printnanny_os'
honeycomb_api_key: '22ffab0ec6af32b2be565bc831555e44'

##
# janus vars
##
janus_install_dir: /opt/janus
janus_admin_url: 'http://localhost:{{ janus_conf["janus.transport.http"]["admin_http_port"] }}{{ janus_conf["janus.transport.http"]["admin_base_path"] }}'
janus_url: 'http://localhost:{{ janus_conf["janus.transport.http"]["http_port"] }}{{ janus_conf["janus.transport.http"]["base_path"] }}'

janus_exec_start_post:
  - >-
    printnanny
    janus-admin
    --host {{ janus_admin_url }}
    add-token
    --token ${JANUS_TOKEN}
    --adminsecret ${JANUS_ADMIN_SECRET}

janus_ssl_enabled: true
janus_ssl_cert: '{{ printnanny_ssl_cert }}'
janus_ssl_key: '{{ printnanny_ssl_key }}'
