---
# defaults file for setup
# defaults file for ansible-role-print-nanny
tflite_version: v2.5.1

printnanny_install_dir: /opt/printnanny
printnanny_cacert_dir: '{{ printnanny_install_dir }}/ca-certificates'
printnanny_data_dir: '{{ printnanny_install_dir }}/data'
printnanny_keys_dir: '{{ printnanny_install_dir }}/keys'
printnanny_keys_private: '{{ printnanny_keys_dir }}/id_ecdsa'
printnanny_keys_public: '{{ printnanny_keys_private }}.pub'

printnanny_backups_dir: "{{ printnanny_install_dir }}/backups"
printnanny_ansible_dir: "{{ printnanny_install_dir }}/ansible"
printnanny_license_zip: /boot/printnanny_license.zip
printnanny_license_json_file: '{{ printnanny_data_dir }}/license.json'
printnanny_public_key: '{{ printnanny_data_dir }}/ecdsa_public.pem'

printnanny_www_dir: '{{ printnanny_install_dir }}/www'
printnanny_www_secret_file: '{{ printnanny_www_dir }}/key'
printnanny_www_templates_dir: '{{ printnanny_www_dir }}/templates'
printnanny_www_address: "0.0.0.0"
printnanny_www_port: 9001
printnanny_www_log_level: "normal"

ansible_facts_path: /etc/ansible/facts.d
printnanny_device_fact: /etc/ansible/facts.d/device.fact
printnanny_license_fact: /etc/ansible/facts.d/license.fact
printnanny_janus_fact: /etc/ansible/facts.d/janus.fact

printnanny_cli_version: 0.11.2
printnanny_cli_repo: 'https://github.com/bitsy-ai/printnanny-cli'
printnanny_cli_url: '{{ printnanny_cli_repo }}/releases/download/v{{ printnanny_cli_version }}/printnanny-{{ ansible_architecture }}-unknown-linux-gnu.tar.gz'
printnanny_www_templates_url: '{{ printnanny_cli_repo }}/releases/download/v{{ printnanny_cli_version }}/printnanny-www-templates.tar.gz'
printnanny_ansible_version: 'ansible>4,<5'
printnanny_update_schedule: '*/15 * * * *'
printnanny_user: printnanny
printnanny_group: printnanny

gcp_lts_ca_primary: https://pki.goog/gtsltsr/gtsltsr.crt
gcp_lts_ca_backup: https://pki.goog/gsr4/GSR4.crt


printnanny_ssl_key_size: 4096
printnanny_ssl_key_type: DSA
printnanny_ssl_dir: '{{ janus_install_dir }}/ssl'
printnanny_ssl_crt_dir: '{{ janus_install_dir }}/ssl/crt'
printnanny_ssl_key_dir: '{{ janus_install_dir }}/ssl/private'
printnanny_ssl_csr_dir: '{{ janus_install_dir }}/ssl/csr'
printnanny_ssl_cert: '{{ printnanny_ssl_crt_dir}}/janus.crt'
printnanny_ssl_key: '{{ printnanny_ssl_key_dir}}/janus.pem'
printnanny_ssl_csr: '{{ printnanny_ssl_csr_dir }}/janus.csr'

printnanny_ssl_country_name: 'US'
printnanny_ssl_email_address: support@print-nanny.com
printnanny_ssl_organization_name: 'Bitsy AI Labs, LLC'
