- name: Render config.toml
  ansible.builtin.template:
    src: config.toml.j2
    dest: '{{ printnanny_config_toml }}'
    mode: 0644
    force: true
    owner: '{{ printnanny_user }}'
  notify:
    - restart printnanny-dash
    - restart mqtt
- include_tasks: metadata/env.yml
- include_tasks: metadata/cert.yml
- include_tasks: metadata/secrets.yml
