---
- name: Update Print Nanny system
  import_playbook: ../system.yml
  vars:
    printnanny_edition: octoprint_desktop
    janus_remote_enabled: true
    janus_local_enabled: false
- hosts: printnanny
  tasks:
    - name: Octoprint role
      include_role:
        name: bitsyai.printnanny.octoprint
    - name: Clean and minimize image
      include_role:
        name: bitsyai.printnanny.common
        tasks_from: clean_image
