- name: Read '{{ printnanny_cmdfile }}'
  ansible.builtin.include_vars:
    file: '{{ printnanny_cmdfile }}'
    name: printnanny_cmd
  tags:
    - cmd
- name: Debug printnanny_cmd
  ansible.builtin.debug:
    var: printnanny_cmd
  tags:
    - cmd
- name: include {{ printnanny_cmd.event_name }} tasks
  include_tasks: 
    file: 'handlers/{{ printnanny_cmd.event_name }}.yml'
    apply:
      tags:
        - cmd
- name: Move {{ printnanny_cmdfile }} to done
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: '{{ printnanny_cmdfile }}'
    dest: '{{ printnanny_cmd_success_dir}}/{{ printnanny_cmdfile | basename }}'
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_user }}'
  tags:
    - cmd
- name: Delete {{ printnanny_cmdfile }}
  become: true
  ansible.builtin.file:
    state: abscent
    path: '{{ printnanny_cmdfile }}'
  tags:
    - cmd