- name: Render journald conf
  become: true
  ansible.builtin.template:
    mode: 0664
    src: systemd/journald.conf.j2
    dest: /etc/systemd/journald.conf
    force: true
    owner: root
    group: root

- name: Configure logrotate.d/rsyslog
  become: true
  ansible.builtin.template:
    src: logrotate.d/rsyslog.conf.j2
    dest: /etc/logrotate.d/rsyslog
    owner: root
    group: root
    mode: 0644
    force: true
