---
- name: User setup
  ansible.builtin.include_tasks: users.yml
  tags:
    - setup
- name: Setup ansible facts.d
  ansible.builtin.include_tasks: factsd.yml
  tags:
    - setup
- name: Slim packages
  ansible.builtin.include_tasks: slim.yml
  tags:
    - setup
- name: Install apt packages
  ansible.builtin.include_tasks: apt.yml
  tags:
    - setup
- name: Configure log rotation
  ansible.builtin.include_tasks: logs.yml
  tags:
    - setup
