---
- name: User setup
  ansible.builtin.import_tasks: users.yml
  tags:
    - setup
- name: Setup ansible facts.d
  ansible.builtin.import_tasks: factsd.yml
  tags:
    - setup
- name: Slim packages
  ansible.builtin.import_tasks: slim.yml
  tags:
    - setup
- name: Install apt packages
  ansible.builtin.import_tasks: apt.yml
  tags:
    - setup
- name: Install log-vacuum service/timer
  ansible.builtin.import_tasks: log.yml
  tags:
    - setup
