---
- name: Install sudo pkg
  become: true
  ansible.builtin.apt:
    name:
      - sudo

- name: 'Configure {{ printnanny_user }} user'
  become: true
  ansible.builtin.user:
    state: present
    shell: /bin/bash
    comment: "PrintNanny service user"
    name: '{{ printnanny_user }}'
    groups: '{{ printnanny_groups }}'
    append: true
  tags:
    - setup

- name: Create {{ octoprint_user }} user
  become: true
  ansible.builtin.user:
    name: "{{ octoprint_user }}"
    state: present
    shell: /bin/bash
    comment: "OctoPrint service user"
    groups:
      - adm
      - dialout
      - gpio
      - i2c
      - input
      - plugdev
      - spi
      - sudo
      - tty
      - video
  tags:
    - setup
    - octoprint


- name: Configure {{ janus_user }} user
  become: true
  ansible.builtin.user:
    name: "{{ janus_user }}"
    state: present
    shell: /bin/bash
    comment: "Janus WebRTC Gateway service user"
    groups:
      - ssl-cert
  tags:
    - setup
    - janus

- name: Copy sudoers.d
  become: true
  ansible.builtin.copy:
    src: sudoers.d/
    dest: /etc/sudoers.d/
    force: true
    check: visudo -c
  tags:
    - setup
