---
# tasks file for users
- name: Create users and groups
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    state: present
  loop: "{{ users }}"
  become: true
  tags:
    - metadata
- name: Add authorized keys
  become: true
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.authorized_key }}"
    exclusive: true
  loop: "{{ users }}"
  tags:
    - metadata
- name: Install sudo pkg
  become: true
  ansible.builtin.apt:
    name:
      - sudo

- name: Configure sudoers
  ansible.builtin.copy:
    dest: "{{ item.file }}"
    content: "{{ item.content }}"
    validate: visudo -cf %s
    mode: 0440
  with_items: "{{ sudoers_files }}"
