---
- name: Install sudo pkg
  become: true
  ansible.builtin.apt:
    name:
      - sudo

- name: 'Configure {{ printnanny_user }} user'
  become: true
  ansible.builtin.user:
    state: present
    shell: /bin/bash
    comment: "PrintNanny service user"
    name: '{{ printnanny_user }}'
    groups: '{{ printnanny_groups }}'
    append: true
  tags:
    - setup

- name: Create {{ octoprint_user }} user
  become: true
  ansible.builtin.user:
    name: "{{ octoprint_user }}"
    state: present
    shell: /bin/bash
    comment: "OctoPrint service user"
    groups:
      - adm
      - dialout
      - gpio
      - i2c
      - input
      - plugdev
      - spi
      - sudo
      - tty
      - video
  tags:
    - setup
    - octoprint


- name: Create {{ janus_user }} user
  become: true
  ansible.builtin.user:
    name: "{{ janus_user }}"
    state: present
    shell: /bin/bash
    comment: "Janus WebRTC Gateway service user"
    groups:
      - ssl-cert
  tags:
    - setup
    - janus

- name: Configure sudoers
  become: true
  ansible.builtin.copy:
    dest: "{{ item.file }}"
    content: "{{ item.content }}"
    validate: visudo -cf %s
    mode: 0440
  with_items: "{{ sudoers_files }}"
