- name: 'Create {{ ansible_env.HOME }}/venv/ansible'
  become_user: '{{ ansible_user }}'
  pip:
    name: 
      - 'pip>21,<22'
      - setuptools
      - wheel
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ ansible_env.HOME }}/venv/ansible'
    extra_args: '--no-cache-dir'

- name: Install ansible into the specified (virtualenv)
  become_user: '{{ ansible_user }}'
  pip:
    name: '{{ printnanny_ansible_version }}'
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ ansible_env.HOME }}/venv/ansible'
    extra_args: '--no-cache-dir'

- name: copy sudoers_ansible
  become: true
  ansible.builtin.copy: 
    src: files/sudoers_ansible 
    dest: /etc/sudoers.d/00_ansible_pwdless.conf
    owner: root 
    group: root 
    mode: 0440

- name: Create ansible.cfg
  ansible.builtin.template:
    mode: 0664
    src: ansible.cfg.j2
    dest: "{{ ansible_env.HOME }}/.ansible.cfg"


- name: Create '{{ ansible_user }}'/.ansible/hosts
  become_user: '{{ ansible_user }}'
  ansible.builtin.copy: 
    src: files/hosts
    dest: '{{ ansible_env.HOME }}/.ansible/hosts'
    mode: 0660

