- name: Clean apt cache
  become: true
  ansible.builtin.command: apt clean
- name: Remove package lists
  become: true
  ansible.builtin.shell: rm -rf /var/lib/apt/lists/*

- name: Ensure machine-id uninitialized
  become: true
  ansible.builtin.copy:
    content: "uninitialized\n"
    mode: '0444'
    dest: /etc/machine-id
- name: Remove dbus machine-id
  become: true
  ansible.builtin.file:
    state: absent
    path: /var/lib/dbus/machine-id
