- name: Update firmware
  become: true
  ansible.builtin.shell:
    cmd: "yes | rpi-update {{ rpi_firmware_version }}"
    creates: /boot/.firmware_revision
  when: ansible_distribution == 'Debian'

- name: Reboot to apply firmware updates
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 360
  when: ansible_distribution == 'Debian'
