- name: Remove x-org / gnome if building headless image
  become: true
  ansible.builtin.apt:
    name:
      - alacarte
      - arandr
      - chromium-browser
      - chromium-browser-l10n
      - chromium-codecs-ffmpeg-extra
      - colord
      - colord-data
      - desktop-base
      - desktop-file-utils
      - gnome-desktop3-data
      - gnome-icon-theme
      - gnome-settings-daemon-common
      - gnome-themes-extra
      - gnome-themes-extra-data
      - gnome-themes-standard
      - gpicview
      - gsettings-desktop-schema
      - gtk-update-icon-cache
      - gtk2-engines
      - gtk2-engines-clearlookspix
      - gtk2-engines-pixbuf
      - gtk2-engines-pixflat
      - gui-pkinst
      - hicolor-icon-theme
      - qt5-style-plugin-cleanlooks
      - qt5-style-plugin-motif
      - qt5-style-plugin-plastique
      - vlc-plugin-qt
      - xserver-common
      - xserver-xorg
      - xserver-xorg-core
      - xserver-xorg-input-all
      - xserver-xorg-input-libinput
      - xserver-xorg-video-all
      - xserver-xorg-video-amdgpu
      - xserver-xorg-video-ati
      - xserver-xorg-video-fbdev
      - xserver-xorg-video-fbturbo
      - xserver-xorg-video-nouveau
      - xserver-xorg-video-radeon
      - xserver-xorg-video-vesa
      - zenity
    state: absent
    purge: true