- name: Remove extra pkgs if building from full Raspi OS img
  become: true
  ansible.builtin.apt:
    name: '{{ item }}'
    state: absent
    purge: true
  loop: rpi_slim_pkgs

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true

- name: Remove useless packages from apt cache
  become: true
  ansible.builtin.apt:
    autoclean: true

- name: Remove /home/pi/Bookshelf
  become: true
  ansible.builtin.file:
    path: /home/pi/Bookshelf
    state: absent
