- name: Update pkg cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Remove extra pkgs if building from full Raspi OS img
  become: true
  ansible.builtin.apt:
    name:
      - bluej
      - dictionaries-common
      - emacsen-common
      - freepats
      - galculator
      - geany
      - ghostscript
      - greenfoot
      - hunspell-en-gb
      - hunspell-en-us
      - javascript-common
      - minecraft-pi
      - nodered
      - oracle-java8-jdk
      - pi-greeter
      - pixflat-icons
      - pocketsphinx-en-us
      - python-minecraftpi
      - python3-mypy
      - qttranslations5-l10n
      - rpd-wallpaper
      - scratch
      - sonic-pi
      - squeak-plugins-scratch
      - squeak-vm
      - system-config-printer-common
      - wolfram-engine
    state: absent
    purge: true

- name: Remove dependencies that are no longer required
  become: true
  ansible.builtin.apt:
    autoremove: true

- name: Remove useless packages from apt cache
  become: true
  ansible.builtin.apt:
    autoclean: true

- name: Remove /home/pi/Bookshelf
  become: true
  ansible.builtin.file:
    path: /home/pi/Bookshelf
    state: absent
