- name: Remove extra pkgs if building from full Raspi OS img
  ansible.builtin.apt:
    name:
      - scratch
      - squeak-plugins-scratch
      - squeak-vm
      - wolfram-engine
      - python-minecraftpi
      - minecraft-pi sonic-pi
      - oracle-java8-jdk
      - bluej
      - libreoffice-common
      - libreoffice-core
      - freepats
      - greenfoot
      - nodered
    state: absent
    autoremove: true
