---
# handlers file for handlers
- name: restart printnanny-janus if running
  ansible.builtin.service_facts:
  notify:
    - check printnanny-janus running


- name: check printnanny-janus running
  ansible.builtin.debug:
    var: ansible_facts.services["printnanny-janus.service"]
  when: ansible_facts.services["printnanny-janus.service"].state == "running" and janus_config_updated.changed
  notify:
    - restart printnanny-janus

- name: restart printnanny-janus
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: printnanny-janus
    no_block: true
    state: restarted