- name: Render printnanny-firstboot.service template
  become: true
  ansible.builtin.template:
    src: printnanny-firstboot.service.j2
    dest: /etc/systemd/system/printnanny-firstboot.service
    mode: 0664
    force: true
  tags:
    - firstboot

- name: Enable firstboot service
  become: true
  ansible.builtin.systemd:
    name: printnanny-firstboot.service
    enabled: true
    no_block: true
  tags:
    - firstboot
