- name: Create set fact printnanny_www_secret_key
  ansible.builtin.set_fact:
    cacheable: true
    printnanny_www_secret_key: "{{ lookup('password', printnanny_www_secret_file + ' chars=hexdigits length=64') }}"
  tags:
    - secret
    - firstboot
    - dash

- name: Render PrintNanny Dashboard Rocket.toml
  ansible.builtin.template:
    mode: 0660
    src: www/Rocket.toml.j2
    dest: '{{ printnanny_www_dir }}/Rocket.toml'
    force: true
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_user }}'
  when: printnanny_www_secret_key is defined
  tags:
    - secret
    - firstboot
    - dash
  notify:
    - restart printnanny-dash
