---
# defaults file for ansible-role-janus-gateway
printnanny_ssl_key_size: 2048
printnanny_ssl_key_type: DSA
printnanny_ssl_dir: '{{ janus_install_dir }}/ssl'
printnanny_ssl_crt_dir: '{{ janus_install_dir }}/ssl/crt'
printnanny_ssl_key_dir: '{{ janus_install_dir }}/ssl/private'
printnanny_ssl_csr_dir: '{{ janus_install_dir }}/ssl/csr'
printnanny_ssl_cert: '{{ printnanny_ssl_crt_dir}}/janus.crt'
printnanny_ssl_key: '{{ printnanny_ssl_key_dir}}/janus.pem'
printnanny_ssl_csr: '{{ printnanny_ssl_csr_dir }}/janus.csr'
janus_auth: {}

cam_rtp_port: 5104
nn_rtp_port: 5105

janus_build_source: true

janus_build_extras:
  audiobridge: false
  mqtt: false
  nanomsg: false
  rabbitmq: false
  recordplay: false
  sip: false
  systemd: true
  websockets: true

janus_user: janus
janus_group: janus
janus_groups:
  - video
janus_install_dir: /opt/janus
janus_build_dir: build
janus_conf_dir: /etc/janus
janus_log_file: /var/log/janus/janus.log
janus_lib_prefix: /usr/local
janus_pid_file: /var/run/janus/janus.pid
janus_env_file: /etc/janus/janus.env


janus_admin_secret_file: '{{ janus_conf_dir }}/janus_admin_secret'
janus_token_file: '{{ janus_conf_dir }}/janus_token'

janus_libwebsockets_repo: https://github.com/warmcat/libwebsockets.git
janus_libwebsockets_version: v3.2-stable

janus_libnice_repo: https://github.com/libnice/libnice
janus_libnice_version: "0.1.18"

janus_usrsctp_repo: https://github.com/sctplab/usrsctp
janus_usrsctp_version: 0.9.5.0

janus_libsrtp_version: "2.2.0"
janus_libsrtp_tarball: "https://github.com/cisco/libsrtp/archive/v{{ janus_libsrtp_version }}.tar.gz"

janus_repo: https://github.com/meetecho/janus-gateway.git
janus_version: 0.11.6
janus_conf:
  janus:
    plugins_folder: "{{ janus_install_dir }}/lib/janus/plugins"
    transports_folder: "{{ janus_install_dir }}/lib/janus/transports"
    events_folder: "{{ janus_install_dir }}/lib/janus/events"
    loggers_folder: "{{ janus_install_dir }}/lib/janus/loggers"
    log_to_stdout: true
    debug_level: 7
    pid_file: "/var/run/janus.pid"
    session_timeout: 60
    candidates_timeout: 45
    reclaim_session_timeout: 0
    no_webrtc_encryption: false
    ignore_unreachable_ice_server: true
  janus.transport.http:
    admin_base_path: "/admin"
    admin_http_port: 7088
    admin_https_port: 7089
    admin_http: true
    admin_https: false
    base_path: "/janus"
    https: false
    https_port: 8089
    http: true
    http_port: 8088

janus_conf_template:
  janus.eventhandler.gelfevh.jcfg: janus.eventhandler.gelfevh.jcfg
  janus.eventhandler.sampleevh.jcfg: janus.eventhandler.sampleevh.jcfg
  janus.eventhandler.wsevh.jcfg: janus.eventhandler.wsevh.jcfg
  janus.jcfg: janus.jcfg
  janus.plugin.audiobridge.jcfg: janus.plugin.audiobridge.jcfg
  janus.plugin.echotest.jcfg: janus.plugin.echotest.jcfg
  janus.plugin.nosip.jcfg: janus.plugin.nosip.jcfg
  janus.plugin.recordplay.jcfg: janus.plugin.recordplay.jcfg
  janus.plugin.sip.jcfg: janus.plugin.sip.jcfg
  janus.plugin.streaming.jcfg: janus.plugin.streaming.jcfg
  janus.plugin.textroom.jcfg: janus.plugin.textroom.jcfg
  janus.plugin.videocall.jcfg: janus.plugin.videocall.jcfg
  janus.plugin.voicemail.jcfg: janus.plugin.voicemail.jcfg
  janus.transport.http.jcfg: janus.transport.http.jcfg
  janus.transport.pfunix.jcfg: janus.transport.pfunix.jcfg
  janus.transport.websockets.jcfg: janus.transport.websockets.jcfg
janus_unit_extra: null
janus_service_unit_extra: null

janus_startup_delay: 30

ansible_facts_path: /etc/ansible/facts.d
janus_fact: /etc/ansible/facts.d/janus.fact

janus_admin_secret: null
janus_token: null

janus_ssl_ciphers: null
janus_ssl_enabled: true
janus_ssl_cert: '{{ printnanny_ssl_cert }}'
janus_ssl_key: '{{ printnanny_ssl_key }}'
janus_ssl_passphrase: null
janus_upgrade_available: true
