---
# vars file for setup

janus_install_dir: /opt/janus
janus_conf_dir: "{{ janus_install_dir }}/etc/janus"
janus_conf:
  janus:
    plugins_folder: "{{ janus_install_dir }}/lib/janus/plugins"
    transports_folder: "{{ janus_install_dir }}/lib/janus/transports"
    events_folder: "{{ janus_install_dir }}/lib/janus/events"
    loggers_folder: "{{ janus_install_dir }}/lib/janus/loggers"
    log_to_stdout: true
    debug_level: 4
    daemonize: false
    pid_file: "/var/run/janus.pid"
    session_timeout: 60
    candidates_timeout: 45
    reclaim_session_timeout: 0
    no_webrtc_encryption: false
    ignore_unreachable_ice_server: true
  janus.transport.http:
    admin_base_path: "/admin"
    admin_http_port: 7088
    admin_https_port: 7889
    admin_http: true
    admin_https: false
    base_path: "/janus"
    https: false
    https_port: 8089
    http: true
    http_port: 8088

janus_conf_template:
  janus.eventhandler.gelfevh.jcfg: janus.eventhandler.gelfevh.jcfg
  janus.eventhandler.sampleevh.jcfg: janus.eventhandler.sampleevh.jcfg
  janus.eventhandler.wsevh.jcfg: janus.eventhandler.wsevh.jcfg
  janus.jcfg: janus.jcfg
  janus.plugin.audiobridge.jcfg: janus.plugin.audiobridge.jcfg
  janus.plugin.echotest.jcfg: janus.plugin.echotest.jcfg
  janus.plugin.nosip.jcfg: janus.plugin.nosip.jcfg
  janus.plugin.recordplay.jcfg: janus.plugin.recordplay.jcfg
  janus.plugin.sip.jcfg: janus.plugin.sip.jcfg
  janus.plugin.streaming.jcfg: janus.plugin.streaming.jcfg
  janus.plugin.textroom.jcfg: janus.plugin.textroom.jcfg
  janus.plugin.videocall.jcfg: janus.plugin.videocall.jcfg
  janus.plugin.voicemail.jcfg: janus.plugin.voicemail.jcfg
  janus.transport.http.jcfg: janus.transport.http.jcfg
  janus.transport.pfunix.jcfg: janus.transport.pfunix.jcfg
  janus.transport.websockets.jcfg: janus.transport.websockets.jcfg
