---
# tasks file for nnstreamer

- name: Add nnstreamer PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:nnstreamer/ppa
    state: present
    codename: focal

- name: Install nnstreamer
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - nnstreamer

- name: Create {{ nn_install_dir }}
  become: true
  ansible.builtin.file:
    state: directory
    path: '{{ nn_install_dir }}'
    mode: 0775

- name: Download {{ nn_model_url }}
  become: true
  ansible.builtin.get_url:
    url: '{{ nn_model_url }}'
    dest: '{{ nn_model_file }}'

- name: Download {{ nn_label_url }}
  become: true
  ansible.builtin.get_url:
    url: '{{ nn_model_url }}'
    dest: '{{ nn_label_file }}'

- name: Download {{ nn_metadata_file }}
  become: true
  ansible.builtin.get_url:
    url: '{{ nn_model_url }}'
    dest: '{{ nn_label_file }}'
