---
- hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'update printnanny system'
    ara_playbook_labels:
      - update
      - printnanny
      - system
  tasks:
    - name: Debug facts.d vars
      ansible.builtin.debug:
        var: ansible_local
    - name: Include janus role
      include_role:
        name: bitsyai.printnanny.janus
