---
- hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'bitsyai.printnanny.firstboot'
    ara_playbook_labels:
      - printnanny
      - firstboot
      - metadata
  roles:
    - bitsyai.printnanny.install
  tasks:
    - name: Run firstboot tasks
      include_role:
        name: bitsyai.printnanny.metadata
        tasks_from: firstboot/main.yml
        vars_from: '{{ printnanny_profile|default("default", true) }}.yml'
      tags:
        - metadata
        - firstboot
