---
- hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'render printnanny metadata for env app'
    ara_playbook_labels:
      - printnanny
      - env
      - metadata
  roles:
    - bitsyai.printnanny.install
  tasks:
    - name: Set /var/run/printnanny/env metadata
      include_role:
        name: bitsyai.printnanny.metadata
        vars_from: '{{ printnanny_profile|default("default", true) }}.yml'
      tags:
        - metadata
        - firstboot
