---
- hosts: all
  gather_facts: true
  tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
    - name: Setup (generic)
      import_role:
        name: bitsyai.rpi.setup
    - name: Setup (generic)
      import_role:
        name: bitsyai.rpi.nebula
    - name: Setup camera module
      import_role:
        name: bitsyai.rpi.camera
    - name: Setup bitsy updater
      import_role:
        name: bitsyai.rpi.updater
    - name: Clean up caches and machine-id
      import_role:
        name: bitsyai.rpi.setup
        tasks_from: clean_image
