---
- name: Install PrintNanny components
  hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'update printnanny system'
    ara_playbook_labels:
      - update
      - printnanny
      - system
  tasks:
    - name: Install common
      include_role:
        name: bitsyai.printnanny.common
        public: true
    - name: Include PrintNanny Edition vars
      include_vars: ../roles/install/vars/{{ printnanny_edition|default("octoprint_desktop", true) }}.yml
      tags:
        - firstboot
    - name: Include PrintNanny Profile Vars
      include_vars: ../roles/install/vars/{{ printnanny_profile|default("default", true) }}.yml
      tags:
        - firstboot
    - name: Install OctoPrint
      include_role:
        name: bitsyai.printnanny.octoprint
      when: (printnanny_edition|default("octoprint_desktop", true) == "octoprint_desktop" or
        printnanny_edition|default("octoprint_lite", true) == "octoprint_lite")
      tags:
        - firstboot
    - name: Install PrintNanny
      include_role:
        name: bitsyai.printnanny.install
        public: true
      tags:
        - firstboot
    - name: Install local Janus Gateway
      include_role:
        name: bitsyai.printnanny.janus
