---
- name: Install PrintNanny components
  hosts: printnanny
  gather_facts: true
  vars:
    ara_playbook_name: 'update printnanny system'
    ara_playbook_labels:
      - update
      - printnanny
      - system
  tasks:
    - name: Install common
      include_role:
        name: bitsyai.printnanny.common
        public: true
    - name: Include PrintNanny Profile Vars
      include_vars: ../roles/metadata/vars/{{ printnanny_profile|default("default", true) }}.yml
    - name: Include PrintNanny Edition vars
      include_vars: ../roles/install/vars/{{ printnanny_edition|default("octoprint_desktop", true) }}.yml
    - name: Install PrintNanny
      include_role:
        name: bitsyai.printnanny.install
        public: true
    - name: Install firstboot service
      include_role:
        name: bitsyai.printnanny.metadata
        tasks_from: install/firstboot.yml
    - name: Install metadata service
      include_role:
        name: bitsyai.printnanny.metadata
        tasks_from: install/metadata.yml
    - name: Install local Janus Gateway
      include_role:
        name: bitsyai.printnanny.janus
      vars:
        janus_ssl_cert: '{{ printnanny_ssl_cert }}'
        janus_ssl_key: '{{ printnanny_ssl_key }}'
        janus_env_file: '{{ printnanny_env }}'
      when: janus_local_enabled
    - name: Install local Janus Gateway
      include_role:
        name: bitsyai.printnanny.janus
        tasks_from: remote.yml
      vars:
        janus_ssl_cert: '{{ printnanny_ssl_cert }}'
        janus_ssl_key: '{{ printnanny_ssl_key }}'
        janus_env_file: '{{ printnanny_env }}'
      when: janus_remote_enabled
    - name: Install OctoPrint
      include_role:
        name: bitsyai.printnanny.octoprint
      when: (printnanny_edition|default("octoprint_desktop", true) == "octoprint_desktop" or
        printnanny_edition|default("octoprint_lite", true) == "octoprint_lite")
