- name: Install gstreamer dependencies
  become: true
  ansible.builtin.apt:
    name:
      - gstreamer1.0-plugins-base-apps
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-tools
      - gstreamer1.0-libav
      - libx264-dev
      - libjpeg-dev
      - libcamera-dev
  tags:
    - setup
  when: ansible_distribution == 'Debian'

- name: Create {{ gstreamer_service_name }} unit
  become: true
  ansible.builtin.template:
    mode: 0664
    src: '{{ gstreamer_service_name }}.j2'
    dest: '/etc/systemd/system/{{ gstreamer_service_name }}'
  tags:
    - setup
