- name: Install gstreamer dependencies
  become: true
  ansible.builtin.apt:
    name:
      - gstreamer1.0-plugins-*
      - gstreamer1.0-tools
      - gstreamer1.0-vaapi
      - gstreamer1.0-x
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev

- name: Create gstreamer.service unit
  become: true
  ansible.builtin.template:
    mode: 0664
    src: cam-rtp.service.j2
    dest: /etc/systemd/system/cam-rtp.service
