- name: Install gstreamer dependencies
  become: true
  ansible.builtin.apt:
    name:
      - gstreamer1.0-plugins-base-apps
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-tools
      - gstreamer1.0-libav
      - libx264-dev
      - libjpeg-dev
      - libcamera-dev
  tags:
    - setup
  when: ansible_distribution == 'Debian'

- name: Create video-rtp.service unit
  become: true
  ansible.builtin.template:
    mode: 0664
    src: video-rtp.service.j2
    dest: /etc/systemd/system/video-rtp.service
  tags:
    - setup
