- name: Install generic gstreamer dependencies
  become: true
  ansible.builtin.apt:
    name:
      - gstreamer1.0-plugins-base-apps
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-tools
      - gstreamer1.0-libav
      - libx264-dev
      - libjpeg-dev
  tags:
    - setup

- name: 'Render {{ gstreamer_service_name }}'
  ansible.builtin.template:
    mode: 0664
    src: '{{ gstreamer_service_name }}.j2'
    dest: '/etc/systemd/system/{{ gstreamer_service_name }}'
    backup: true
    force: true
  notify: restart gstreamer
