- name: Install ara into ansible virtual env
  become_user: '{{ updater_user }}'
  ansible.builtin.pip:
    name:
      - '{{ ara_version }}'
  when: ara_enabled

# get ansible.cfg values for ara e.g.
# [defaults]
# callback_plugins=/home/leigh/.local/lib/python3.8/site-packages/ara/plugins/callback
# action_plugins=/home/leigh/.local/lib/python3.8/site-packages/ara/plugins/action
# lookup_plugins=/home/leigh/.local/lib/python3.8/site-packages/ara/plugins/lookup

- name: Get ara plugin configs
  become_user: '{{ updater_user }}'
  ansible.builtin.command: '{{ ansible_venv }}/bin/python -m ara.setup.ansible'
  register: ara_plugin_setup
  when: ara_enabled
