- name: Create ansible-pull user
  ansible.builtin.user:
    name: "{{ ansible_pull_user }}"
    state: present
    shell: /sbin/nologin
    comment: "Ansible service user"
  become: true

- name: Install sudo pkg
  become: true
  ansible.builtin.apt:
    name:
      - sudo

- name: Configure ansible sudoers
  become: true
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/00_ansible_pwdless.conf"
    content: "{{ ansible_pull_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
    mode: "0644"

- name: Install apt dependencies
  become: true
  ansible.builtin.apt:
    name:
      - pkg-config
      - python3-dev
      - python3-pip
      - python3-venv
      # required by ansible.builtin.package_facts
      - python3-apt
      - systemd
      - systemd-cron

- name: Create /etc/ansible
  become: true
  file:
    path: /etc/ansible
    state: directory
    
- name: 'Create ansible virtual env'
  become_user: '{{ ansible_pull_user }}'
  pip:
    name:
      - 'pip>21,<22'
      - setuptools
      - wheel
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ ansible_pull_venv }}'
    extra_args: '--no-cache-dir'

- name: Install ansible into the specified (virtualenv)
  become_user: '{{ ansible_pull_user }}'
  pip:
    name: '{{ ansible_pull_version }}'
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv: '{{ ansible_pull_venv }}'
    extra_args: '--no-cache-dir'

- name: Setup passwordless sudo for ansible user
  become: true
  ansible.builtin.copy:
    content: '%{{ ansible_pull_user }} ALL=(ALL) NOPASSWD: ALL }}'
    dest: /etc/sudoers.d/00_ansible_pwdless.conf
    owner: root
    group: root
    mode: 0440

- name: Create ansible.cfg
  become: true
  ansible.builtin.template:
    mode: 0664
    src: ansible.cfg.j2
    dest: "/etc/ansible/ansible.cfg"

- name: Create /etc/ansible/hosts
  become: true
  ansible.builtin.copy:
    src: files/hosts
    dest: '/etc/ansible/hosts'
    mode: 0660

- name: Create ansible-pull systemd slice
  become: true
  ansible.builtin.template:
    mode: 0664
    src: ansible_pull.slice.j2
    dest: '/etc/systemd/system/ansible_pull.slice'

- name: Create ansible-pull systemd timers
  become: true
  ansible.builtin.template:
    mode: 0664
    src: ansible_pull.timer.j2
    dest: '/etc/systemd/system/{{ item.name }}.timer'
  with_items: '{{ ansible_pull_items }}'

- name: Create ansible-pull systemd units
  become: true
  ansible.builtin.template:
    mode: 0664
    src: ansible_pull.service.j2
    dest: '/etc/systemd/system/{{ item.name }}.service'
  with_items: '{{ ansible_pull_items }}'

- name: Enable units
  become: true
  ansible.builtin.systemd:
    name: '{{ item.name }}'
    state: started
    enabled: true
    daemon_reload: true
  with_items: '{{ ansible_pull_items }}'
