- name: Task name
  ansible.builtin.stat:
    path: '{{ printnanny_runtime_dir }}'
  register: printnanny_cache

- name: Render printnanny.env
  become_user: '{{ printnanny_user }}'
  ansible.builtin.template:
    src: printnanny.env.j2
    owner: '{{ printnanny_user }}'
    dest: '{{ printnanny_env }}'
    mode: 0664
    force: true
  when: printnanny_cache.stat.exists
  tags:
    - secret
    - env
    - metadata
  notify:
    - restart printnanny-metadata
    - restart printnanny-dash
    - restart mqtt


- name: Render printnanny.sh
  become_user: '{{ printnanny_user }}'
  ansible.builtin.template:
    src: printnanny.sh.j2
    owner: '{{ printnanny_user }}'
    dest: '{{ printnanny_env_sh }}'
    mode: 0770
    force: true
  when: printnanny_cache.stat.exists
  tags:
    - secret
    - env
    - metadata
  notify:
    - restart printnanny-metadata
    - restart printnanny-dash
    - restart mqtt
