---
- name: 'Configure {{ printnanny_profile_dir }}'
  become: true
  ansible.builtin.file:
    state: directory
    path: '{{ printnanny_profile_dir }}'
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_group }}'
    mode: 0755

- include_tasks: boot_config.yml
- include_tasks: apt.yml
- include_tasks: nginx.yml
- include_tasks: camera.yml
- include_tasks: monitor.yml
- include_tasks: cli.yml
- include_tasks: www.yml
- include_tasks: mqtt.yml
- include_tasks: update.yml
- include_tasks: 
    file: firstboot/main.yml
    apply:
          tags:
            - cmd
  tags:
    - firstboot

- name: Render printnanny-ansible-collection.service
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/collection.service.j2
    dest: /etc/systemd/system/printnanny-ansible-collection.service
    force: true

- name: Enable printnanny-ansible-collection.service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: printnanny-ansible-collection
    no_block: true

- name: Render printnanny-cmd.service
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/cmd.service.j2
    dest: /etc/systemd/system/printnanny-cmd.service
    force: true

- name: Render printnanny-cmd.path
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/cmd.path.j2
    dest: /etc/systemd/system/printnanny-cmd.path
    force: true

- name: Enable printnanny-cmd.service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: printnanny-cmd.service
    no_block: true

- name: Enable printnanny-cmd.path
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: printnanny-cmd.path
    no_block: true

- name: Render printnanny.target
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/printnanny.target.j2
    dest: /etc/systemd/system/printnanny.target
    force: true
  notify:
    - enable printnanny.target

- name: Render printnanny-firstboot.service template
  become: true
  ansible.builtin.template:
    src: printnanny-firstboot.service.j2
    dest: /etc/systemd/system/printnanny-firstboot.service
    mode: 0664
    force: true
  tags:
    - firstboot
  notify:
    - enable printnanny-firstboot.service

- name: Render printnanny-setup.target
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/printnanny-setup.target.j2
    dest: /etc/systemd/system/printnanny-setup.target
    force: true
  notify:
    - enable printnanny-setup.target

- name: Render crashdump script
  become: true
  ansible.builtin.template:
    src: crashdump.sh.j2
    dest: /usr/local/bin/printnanny-crashdump
    mode: 0755

- name: 'Configure /etc/printnanny'
  become: true
  ansible.builtin.file:
    state: directory
    path: '/etc/printnanny'
    mode: 0755

- name: Render /etc/printnanny-os-release
  become: true
  ansible.builtin.template:
    src: os-release.j2
    dest: /etc/printnanny/os-release
    mode: 0755

- name: Clean ansible_async dir
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/.ansible_async"
    state: absent
