---
- name: 'Configure {{ printnanny_profile_dir }}'
  become: true
  ansible.builtin.file:
    state: directory
    path: '{{ printnanny_profile_dir }}'
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_group }}'
    mode: 0755
  tags:
    - metadata

- import_tasks: boot_config.yml
- import_tasks: apt.yml
- import_tasks: nginx.yml
- import_tasks: camera.yml
- import_tasks: monitor.yml
- import_tasks: cli.yml
- import_tasks: www.yml
- import_tasks: mqtt.yml
- name: Clean ansible_async dir
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/.ansible_async"
    state: absent

- name: Render printnanny-ansible-collection.service
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/collection.service.j2
    dest: /etc/systemd/system/printnanny-ansible-collection.service
    force: true
  tags:
    - metadata

- name: Enable printnanny-ansible-collection.service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: printnanny-ansible-collection.service
    no_block: true
  tags:
    - metadata

- name: Render printnanny-cmd.service
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/cmd.service.j2
    dest: /etc/systemd/system/printnanny-cmd.service
    force: true
  tags:
    - metadata

- name: Render printnanny-cmd.path
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/cmd.path.j2
    dest: /etc/systemd/system/printnanny-cmd.path
    force: true
  tags:
    - metadata

- name: Enable printnanny-cmd.service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: printnanny-cmd.service
    no_block: true
  tags:
    - metadata

- name: Enable printnanny-cmd.path
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: printnanny-cmd.path
    no_block: true
  tags:
    - metadata


- name: Render printnanny.target
  become: true
  ansible.builtin.template:
    mode: 0644
    src: systemd/printnanny.target.j2
    dest: /etc/systemd/system/printnanny.target
    force: true
  tags:
    - metadata

- name: Enable printnanny.target
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: printnanny.target
    no_block: true
    daemon_reload: true
  tags:
    - metadata

- name: Render crashdump script
  become: true
  ansible.builtin.template:
    src: crashdump.sh.j2
    dest: /usr/local/bin/printnanny-crashdump
    mode: 0755

- name: 'Configure /etc/printnanny'
  become: true
  ansible.builtin.file:
    state: directory
    path: '/etc/printnanny'
    mode: 0755


- name: Render /etc/printnanny-os-release
  become: true
  ansible.builtin.template:
    src: os-release.j2
    dest: /etc/printnanny/os-release
    mode: 0755
