- name: Create printnanny-events.service unit
  become: true
  ansible.builtin.template:
    mode: 0664
    src: systemd/mqtt.service.j2
    dest: /etc/systemd/system/printnanny-events.service
    force: true
  notify:
    - restart printnanny-events

- name: Enable mqtt service
  become: true
  ansible.builtin.systemd:
    service: printnanny-events
    enabled: true
    no_block: true
