- name: Create printnanny-mqtt.service unit
  become: true
  ansible.builtin.template:
    mode: 0664
    src: systemd/mqtt.service.j2
    dest: /etc/systemd/system/printnanny-mqtt.service
    force: true

- name: Enable mqtt.service
  ansible.builtin.systemd:
    name: printnanny-mqtt
    enabled: true
    no_block: true
