- name: Install NGINX
  become: true
  include_role:
    name: nginxinc.nginx_core.nginx
  vars:
    nginx_start: false
    nginx_setup_license: false
    nginx_logrotate_conf_enable: false
    nginx_modules:
      - njs

- name: Ensure log dir exists
  become: true
  ansible.builtin.file:
    state: directory
    path: '{{ printnanny_log_dir }}'
    owner: '{{ printnanny_user }}'
    group: '{{ printnanny_user }}'
    mode: 0755
  when: printnanny_log_dir is defined

- name: Configure NGINX
  become: true
  include_role:
    name: nginxinc.nginx_core.nginx_config
  vars:
    nginx_config_debug_output: true

- name: Render /etc/nginx/conf.d/servers.conf
  become: true
  ansible.builtin.template:
    src: nginx/nginx.servers.conf.j2
    dest: /etc/nginx/conf.d/servers.conf
    mode: 0644
  notify:
    - reload nginx

- name: Render /etc/nginx/conf.d/printnanny.locations
  become: true
  ansible.builtin.template:
    src: nginx/nginx.locations.j2
    dest: /etc/nginx/conf.d/printnanny.locations
    mode: 0644
  notify:
    - reload nginx

- name: Enable nginx.service
  become: true
  ansible.builtin.systemd:
    name: nginx.service
    enabled: true
