name: Bump version
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Set output
      id: git
      run: echo ::set-output name=git_branch::${GITHUB_REF#refs/*/}
    - name: Bump version (dry run)
      id: tags
      uses: bitsy-ai/github-tag-action@1.37.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true
        RELEASE_BRANCHES: "main"
        PRERELEASE_SUFFIX: "nightly"
    - name: Commit version bump message
      run: |
        ./tools/bump-version.sh ${{ steps.tags.outputs.tag }} ${{ steps.tags.outputs.new_tag }} ${{ steps.git.outputs.git_branch }} 
    - name: Bump version and push tag
      uses: bitsy-ai/github-tag-action@1.37.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: false
        RELEASE_BRANCHES: "main"
        PRERELEASE_SUFFIX: "nightly"
    - name: Send Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.PRINT_NANNY_DISCORD_DEPLOY_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: |
            🥧 **Hot & Fresh Configs** {{ EVENT_PAYLOAD.repository.full_name }}@{{ GITHUB_SHA }}
            **Version**: `${{ steps.tags.outputs.new_tag }}`
            **Channel**: `${{ steps.git.outputs.git_branch }}`
            **Release Notes** https://github.com/bitsy-ai/ansible-collection-rpi/releases/tag/v${{ steps.tags.outputs.new_tag }}