name: Publish Release Notes
on:
  release:
    # Sequence of patterns matched against refs/tags
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Send Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.PRINT_NANNY_DISCORD_DEPLOY_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: |
            🥧 **New Print Nanny OS Version**
            `{{ EVENT_PAYLOAD.repository.full_name }}@{{ GITHUB_SHA }}`
            **Version**: `${{ github.ref }}`
            **Release Notes** https://github.com/bitsy-ai/ansible-collection-rpi/releases/tag/${{ github.ref }}
