name: Ansible Tests
on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
jobs:
    sanity:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            path: "${{ github.repository }}"
        - name: Perform sanity testing with ansible-test
          uses: leigh-johnson/ansible-test-gh-action@ljohnson-tags
          with:
            docker-image: ubuntu2004
            ansible-core-version: stable-2.12
            python-version: 3.8
            target-python-version: 3.8
            testing-type: sanity
    integration:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          group:
            - group1
            - group2
            - group3
            - group5
            - group6
            - group7
          include:
            - group: group7
              tags: metadata
      steps:
        - uses: actions/checkout@v2
          with:
            path: "${{ github.repository }}"
        - uses: actions/setup-python@v2
          with:
            python-version: '3.8'
            cache: 'pip'
        - run: pip install jinja2>=3
        - name: Perform integration testing with ansible-test
          uses: leigh-johnson/ansible-test-gh-action@ljohnson-tags
          with:
            ansible-core-version: stable-2.12
            docker-image: ubuntu2004
            python-version: 3.8
            target-python-version: 3.8
            target: "${{ matrix.group }}/"
            testing-type: integration
            test-deps: >-
              ansible.posix
              community.general
              community.crypto
              nginxinc.nginx_core
            tags: ${{ matrix.tags }}
