name: Ansible Tests
on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel
jobs:
    sanity:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            path: "${{ github.repository }}"
        - name: Perform sanity testing with ansible-test
          uses: ansible-community/ansible-test-gh-action@release/v1
          with:
            docker-image: ubuntu2004
            ansible-core-version: stable-2.11
            python-version: 3.8
            target-python-version: 3.8
            testing-type: sanity
    integration:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          group:
            - group1
            - group2
            - group3
            - group4
            - group5
            - group6
      steps:
        - uses: actions/checkout@v2
          with:
            path: "${{ github.repository }}"
        - name: Perform integration testing with ansible-test
          uses: ansible-community/ansible-test-gh-action@release/v1
          with:
            ansible-core-version: stable-2.11
            docker-image: ubuntu2004
            pre-test-cmd: echo This runs before the ansible-test invocation
            python-version: 3.8
            target-python-version: 3.8
            target: "${{ matrix.group }}/"
            testing-type: integration
            test-deps: >-
              ansible.posix
              community.general
              community.crypto
            verbosity: -vvv
